import { defineConfig, globalIgnores } from 'eslint/config'
import nextVitals from 'eslint-config-next/core-web-vitals'
import nextTs from 'eslint-config-next/typescript'

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  {
    rules: {
      // Underscore-prefixed names are deliberately unused (destructured-out fields).
      '@typescript-eslint/no-unused-vars': ['warn', { argsIgnorePattern: '^_', varsIgnorePattern: '^_' }],
    },
  },
  {
    // Editor-only thumbnails and previews: small, already optimised through /_next/image or
    // shown inside the admin, where next/image isn't available.
    files: ['components/studio/**', 'components/admin/**'],
    rules: { '@next/next/no-img-element': 'off' },
  },
  globalIgnores([
    '.next/**',
    'out/**',
    'build/**',
    'next-env.d.ts',
    // generated by Payload
    'app/(payload)/admin/importMap.js',
    'payload-types.ts',
    'migrations/**',
    '.agents/**',
  ]),
])

export default eslintConfig
