/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    projects: Project;
    media: Media;
    inquiries: Inquiry;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    inquiries: InquiriesSelect<false> | InquiriesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    home: Home;
    about: About;
    site: Site;
  };
  globalsSelect: {
    home: HomeSelect<false> | HomeSelect<true>;
    about: AboutSelect<false> | AboutSelect<true>;
    site: SiteSelect<false> | SiteSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Drag rows to set the order projects appear on the site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  _order?: string | null;
  title: string;
  /**
   * One or two sentences. Shown on project cards and in search/social previews.
   */
  summary: string;
  /**
   * The thumbnail and the big image at the top of the case study. Landscape 16:10 works best.
   */
  cover: number | Media;
  /**
   * What the client needed.
   */
  brief?: string | null;
  /**
   * What you did and why.
   */
  approach?: string | null;
  /**
   * What happened after launch. Keep it factual.
   */
  outcome?: string | null;
  layout?:
    | (
        | {
            image: number | Media;
            caption?: string | null;
            width?: ('contained' | 'wide' | 'full') | null;
            /**
             * Optional backdrop colour, e.g. #111111
             */
            background?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'image';
          }
        | {
            images: (number | Media)[];
            columns?: ('2' | '3' | '4') | null;
            aspect?: ('auto' | 'square' | 'portrait' | 'story' | 'landscape') | null;
            width?: ('contained' | 'wide' | 'full') | null;
            caption?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'gallery';
          }
        | {
            heading?: string | null;
            body: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            before: number | Media;
            after: number | Media;
            caption?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'beforeAfter';
          }
        | {
            heading?: string | null;
            colours?:
              | {
                  hex: string;
                  name?: string | null;
                  note?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'palette';
          }
        | {
            heading?: string | null;
            fonts?:
              | {
                  family: string;
                  usage?: string | null;
                  /**
                   * Optional image of the typeface in use
                   */
                  specimen?: (number | null) | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'typography';
          }
        | {
            /**
             * Upload an MP4 (plays muted on loop, like a GIF)…
             */
            file?: (number | null) | Media;
            /**
             * …or paste a YouTube / Vimeo link
             */
            embed?: string | null;
            caption?: string | null;
            width?: ('contained' | 'wide' | 'full') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'video';
          }
        | {
            quote: string;
            name?: string | null;
            title?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'quote';
          }
        | {
            heading?: string | null;
            items?:
              | {
                  value: string;
                  label: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'stats';
          }
      )[]
    | null;
  /**
   * Defaults to the project title.
   */
  metaTitle?: string | null;
  /**
   * Defaults to the summary.
   */
  metaDescription?: string | null;
  /**
   * Image shown when the link is shared (1200×630). Defaults to the cover.
   */
  ogImage?: (number | null) | Media;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  /**
   * Show on the homepage
   */
  featured?: boolean | null;
  client: string;
  year: string;
  disciplines: ('social' | 'brand' | 'web' | 'print' | 'packaging' | 'illustration' | 'motion')[];
  /**
   * e.g. Art direction, Layout system
   */
  role?: string[] | null;
  /**
   * Link to the live site or post, if public
   */
  liveUrl?: string | null;
  /**
   * Hex colour used for this project’s accents, e.g. #F5C400
   */
  accent?: string | null;
  /**
   * Small print shown at the end (NDA, placeholder images, etc.)
   */
  note?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Every image and video used on the site. Upload big (up to 2560px wide); the site resizes for each screen.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image for screen readers and search engines, e.g. "Matchday poster for Arsenal v Chelsea".
   */
  alt: string;
  caption?: string | null;
  blurDataURL?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries".
 */
export interface Inquiry {
  id: number;
  name: string;
  email: string;
  service?: string | null;
  budget?: string | null;
  message: string;
  status?: ('new' | 'replied' | 'archived') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'inquiries';
        value: number | Inquiry;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  _order?: T;
  title?: T;
  summary?: T;
  cover?: T;
  brief?: T;
  approach?: T;
  outcome?: T;
  layout?:
    | T
    | {
        image?:
          | T
          | {
              image?: T;
              caption?: T;
              width?: T;
              background?: T;
              id?: T;
              blockName?: T;
            };
        gallery?:
          | T
          | {
              images?: T;
              columns?: T;
              aspect?: T;
              width?: T;
              caption?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              heading?: T;
              body?: T;
              id?: T;
              blockName?: T;
            };
        beforeAfter?:
          | T
          | {
              before?: T;
              after?: T;
              caption?: T;
              id?: T;
              blockName?: T;
            };
        palette?:
          | T
          | {
              heading?: T;
              colours?:
                | T
                | {
                    hex?: T;
                    name?: T;
                    note?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        typography?:
          | T
          | {
              heading?: T;
              fonts?:
                | T
                | {
                    family?: T;
                    usage?: T;
                    specimen?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        video?:
          | T
          | {
              file?: T;
              embed?: T;
              caption?: T;
              width?: T;
              id?: T;
              blockName?: T;
            };
        quote?:
          | T
          | {
              quote?: T;
              name?: T;
              title?: T;
              id?: T;
              blockName?: T;
            };
        stats?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    value?: T;
                    label?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  metaTitle?: T;
  metaDescription?: T;
  ogImage?: T;
  generateSlug?: T;
  slug?: T;
  featured?: T;
  client?: T;
  year?: T;
  disciplines?: T;
  role?: T;
  liveUrl?: T;
  accent?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  blurDataURL?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries_select".
 */
export interface InquiriesSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  service?: T;
  budget?: T;
  message?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: number;
  headline: string;
  intro?: string | null;
  /**
   * Up to 5 pieces of your best work shown in the hero. Leave empty to use the featured projects’ covers.
   */
  heroImages?: (number | Media)[] | null;
  workHeading?: string | null;
  workIntro?: string | null;
  servicesHeading?: string | null;
  servicesIntro?: string | null;
  services?:
    | {
        title: string;
        description?: string | null;
        deliverables?: string[] | null;
        /**
         * Leave empty to hide the price
         */
        priceFrom?: number | null;
        currency?: ('KES' | 'USD') | null;
        unit?: string | null;
        id?: string | null;
      }[]
    | null;
  clients?:
    | {
        name: string;
        url?: string | null;
        /**
         * Optional. A single-colour SVG or PNG looks best.
         */
        logo?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  testimonials?:
    | {
        quote: string;
        name: string;
        title?: string | null;
        photo?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  contactHeading?: string | null;
  contactIntro?: string | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about".
 */
export interface About {
  id: number;
  headline: string;
  photo?: (number | null) | Media;
  /**
   * A short paragraph shown on the homepage
   */
  short?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  experience?:
    | {
        role: string;
        company?: string | null;
        years?: string | null;
        id?: string | null;
      }[]
    | null;
  skills?: string[] | null;
  tools?: string[] | null;
  /**
   * Optional downloadable CV or PDF portfolio
   */
  cv?: (number | null) | Media;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site".
 */
export interface Site {
  id: number;
  name: string;
  studio?: string | null;
  /**
   * e.g. Graphic designer & social media creative
   */
  role: string;
  location?: string | null;
  /**
   * Shown in the footer and contact section, e.g. "Booking projects for October"
   */
  availability?: string | null;
  email: string;
  /**
   * International format, e.g. +254 720 949 086
   */
  phone?: string | null;
  /**
   * Show a WhatsApp button using the phone number above
   */
  whatsapp?: boolean | null;
  /**
   * Only profiles with a full URL are shown.
   */
  socials?:
    | {
        platform: 'instagram' | 'behance' | 'dribbble' | 'linkedin' | 'x' | 'facebook' | 'tiktok';
        url: string;
        id?: string | null;
      }[]
    | null;
  metaDescription?: string | null;
  /**
   * Default image when a page is shared (1200×630)
   */
  ogImage?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  headline?: T;
  intro?: T;
  heroImages?: T;
  workHeading?: T;
  workIntro?: T;
  servicesHeading?: T;
  servicesIntro?: T;
  services?:
    | T
    | {
        title?: T;
        description?: T;
        deliverables?: T;
        priceFrom?: T;
        currency?: T;
        unit?: T;
        id?: T;
      };
  clients?:
    | T
    | {
        name?: T;
        url?: T;
        logo?: T;
        id?: T;
      };
  testimonials?:
    | T
    | {
        quote?: T;
        name?: T;
        title?: T;
        photo?: T;
        id?: T;
      };
  contactHeading?: T;
  contactIntro?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about_select".
 */
export interface AboutSelect<T extends boolean = true> {
  headline?: T;
  photo?: T;
  short?: T;
  body?: T;
  experience?:
    | T
    | {
        role?: T;
        company?: T;
        years?: T;
        id?: T;
      };
  skills?: T;
  tools?: T;
  cv?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site_select".
 */
export interface SiteSelect<T extends boolean = true> {
  name?: T;
  studio?: T;
  role?: T;
  location?: T;
  availability?: T;
  email?: T;
  phone?: T;
  whatsapp?: T;
  socials?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  metaDescription?: T;
  ogImage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}