/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    projects: Project;
    services: Service;
    posts: Post;
    media: Media;
    inquiries: Inquiry;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    inquiries: InquiriesSelect<false> | InquiriesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    footer: Footer;
    theme: Theme;
    site: Site;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    theme: ThemeSelect<false> | ThemeSelect<true>;
    site: SiteSelect<false> | SiteSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Every page on the site. Open one to add, reorder, hide or edit its sections.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  /**
   * Used in the admin and as the default browser-tab and search title.
   */
  title: string;
  sections?:
    | (
        | {
            /**
             * Above the headline. {count} becomes the number of clients. Leave empty to hide.
             */
            trustedText?: string | null;
            /**
             * Wrap words in *asterisks* to give them a hand-drawn underline, e.g. I craft *experiences*.
             */
            headline: string;
            intro?: string | null;
            /**
             * The short line beside the button.
             */
            ctaText?: string | null;
            button?: {
              label?: string | null;
              /**
               * A page (/about), a section (/#contact) or a full URL.
               */
              url?: string | null;
              variant?: ('default' | 'light' | 'dark' | 'accent' | 'outline' | 'ghost') | null;
            };
            /**
             * Shown at the start of the strip of client names.
             */
            clientsLabel?: string | null;
            /**
             * The names scrolling under the button.
             */
            clients?:
              | {
                  name: string;
                  url?: string | null;
                  id?: string | null;
                }[]
              | null;
            /**
             * Up to three. Leave empty to use the first three featured projects.
             */
            projects?: (number | Project)[] | null;
            /**
             * Leave anything empty to keep the design’s default.
             */
            style?: {
              background?: string | null;
              text?: string | null;
              accent?: string | null;
              paddingTop?: number | null;
              paddingBottom?: number | null;
              minHeight?: number | null;
              width?: ('default' | 'narrow' | 'wide' | 'full') | null;
              align?: ('default' | 'left' | 'center') | null;
              visibility?: ('all' | 'desktop' | 'mobile') | null;
            };
            hidden?: boolean | null;
            /**
             * Optional. Lets menu links jump here, e.g. “work” for /#work. Letters, numbers and dashes only.
             */
            anchor?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            /**
             * The small line above the heading.
             */
            eyebrow?: string | null;
            heading?: string | null;
            intro?: string | null;
            layout?: ('feature' | 'carousel') | null;
            /**
             * In order: the first is the large case study. Leave empty to use every featured project.
             */
            projects?: (number | Project)[] | null;
            /**
             * Added to the project covers on the tilted wall.
             */
            extraImages?: (number | Media)[] | null;
            showWall?: boolean | null;
            link?: {
              label?: string | null;
              /**
               * A page (/about), a section (/#contact) or a full URL.
               */
              url?: string | null;
              variant?: ('default' | 'light' | 'dark' | 'accent' | 'outline' | 'ghost') | null;
            };
            /**
             * Leave anything empty to keep the design’s default.
             */
            style?: {
              background?: string | null;
              text?: string | null;
              accent?: string | null;
              paddingTop?: number | null;
              paddingBottom?: number | null;
              minHeight?: number | null;
              width?: ('default' | 'narrow' | 'wide' | 'full') | null;
              align?: ('default' | 'left' | 'center') | null;
              visibility?: ('all' | 'desktop' | 'mobile') | null;
            };
            hidden?: boolean | null;
            /**
             * Optional. Lets menu links jump here, e.g. “work” for /#work. Letters, numbers and dashes only.
             */
            anchor?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'workShowcase';
          }
        | {
            layout?: ('portrait' | 'editorial' | 'banner') | null;
            /**
             * The small line above the heading.
             */
            eyebrow?: string | null;
            /**
             * Under your name (editorial layout).
             */
            role?: string | null;
            /**
             * Editorial layout: each tab swaps the heading, text and table on the right.
             */
            tabs?:
              | {
                  label: string;
                  heading: string;
                  text?: string | null;
                  /**
                   * Numbers at the start of a value (50+, 3.5M+, 100%) count up when the section comes into view.
                   */
                  rows?:
                    | {
                        value: string;
                        label: string;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            /**
             * Followed by your first name, e.g. “Hi, I’m” → “Hi, I’m Humphrey,”.
             */
            greeting?: string | null;
            heading: string;
            /**
             * A cut-out portrait (transparent PNG or WebP) looks best. Portrait layout: any portrait photo works.
             */
            photo?: (number | null) | Media;
            /**
             * Portrait layout: a second portrait. A “Change the mood” button swaps between the two.
             */
            moodPhoto?: (number | null) | Media;
            /**
             * Portrait layout: short labels stuck on the photo, e.g. “Always curious”. The site tagline is added on its own.
             */
            stickers?: string[] | null;
            /**
             * Portrait layout: a small line under the photo, e.g. “Designer by practice. Explorer by nature.”
             */
            caption?: string | null;
            /**
             * Continues the greeting, e.g. “a Senior Designer specialising in”. The list below finishes it.
             */
            intro?: string | null;
            /**
             * Short points, one per line. Type one and press Enter.
             */
            expertise?: string[] | null;
            servicesHeading?: string | null;
            /**
             * Red banner layout: pick from Content → Services; each links to its own page. Leave empty to list every published service.
             */
            services?: (number | Service)[] | null;
            cta?: {
              label?: string | null;
              /**
               * A page (/about), a section (/#contact) or a full URL.
               */
              url?: string | null;
              variant?: ('default' | 'light' | 'dark' | 'accent' | 'outline' | 'ghost') | null;
            };
            stats?:
              | {
                  value: string;
                  label: string;
                  id?: string | null;
                }[]
              | null;
            /**
             * The giant word at the bottom. Defaults to your first name.
             */
            bigName?: string | null;
            link?: {
              label?: string | null;
              /**
               * A page (/about), a section (/#contact) or a full URL.
               */
              url?: string | null;
              variant?: ('default' | 'light' | 'dark' | 'accent' | 'outline' | 'ghost') | null;
            };
            /**
             * Leave anything empty to keep the design’s default.
             */
            style?: {
              background?: string | null;
              text?: string | null;
              accent?: string | null;
              paddingTop?: number | null;
              paddingBottom?: number | null;
              minHeight?: number | null;
              width?: ('default' | 'narrow' | 'wide' | 'full') | null;
              align?: ('default' | 'left' | 'center') | null;
              visibility?: ('all' | 'desktop' | 'mobile') | null;
            };
            hidden?: boolean | null;
            /**
             * Optional. Lets menu links jump here, e.g. “work” for /#work. Letters, numbers and dashes only.
             */
            anchor?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'aboutBanner';
          }
        | {
            heading?: string | null;
            lead?: string | null;
            /**
             * Finishes the sentence. Type one and press Enter.
             */
            roles?: string[] | null;
            /**
             * Leave anything empty to keep the design’s default.
             */
            style?: {
              background?: string | null;
              text?: string | null;
              accent?: string | null;
              paddingTop?: number | null;
              paddingBottom?: number | null;
              minHeight?: number | null;
              width?: ('default' | 'narrow' | 'wide' | 'full') | null;
              align?: ('default' | 'left' | 'center') | null;
              visibility?: ('all' | 'desktop' | 'mobile') | null;
            };
            hidden?: boolean | null;
            /**
             * Optional. Lets menu links jump here, e.g. “work” for /#work. Letters, numbers and dashes only.
             */
            anchor?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'audience';
          }
        | {
            /**
             * The small line above the heading.
             */
            eyebrow?: string | null;
            heading?: string | null;
            /**
             * A line under the heading, e.g. “Vision → Design → Performance”.
             */
            lead?: string | null;
            layout?: ('circuit' | 'steps' | 'stack') | null;
            steps?:
              | {
                  title: string;
                  icon?:
                    | (
                        | 'compass'
                        | 'pen'
                        | 'chat'
                        | 'rocket'
                        | 'layers'
                        | 'spark'
                        | 'bulb'
                        | 'chart'
                        | 'sliders'
                        | 'checkCircle'
                      )
                    | null;
                  /**
                   * How long this phase usually takes, e.g. “2–3 days”. Shown beside the step’s title (timeline layout).
                   */
                  duration?: string | null;
                  description?: string | null;
                  points?: string[] | null;
                  /**
                   * Leave empty to use a project cover.
                   */
                  image?: (number | null) | Media;
                  id?: string | null;
                }[]
              | null;
            /**
             * Leave anything empty to keep the design’s default.
             */
            style?: {
              background?: string | null;
              text?: string | null;
              accent?: string | null;
              paddingTop?: number | null;
              paddingBottom?: number | null;
              minHeight?: number | null;
              width?: ('default' | 'narrow' | 'wide' | 'full') | null;
              align?: ('default' | 'left' | 'center') | null;
              visibility?: ('all' | 'desktop' | 'mobile') | null;
            };
            hidden?: boolean | null;
            /**
             * Optional. Lets menu links jump here, e.g. “work” for /#work. Letters, numbers and dashes only.
             */
            anchor?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'process';
          }
        | {
            /**
             * The small line above the heading.
             */
            eyebrow?: string | null;
            heading?: string | null;
            intro?: string | null;
            layout?: ('deck' | 'cards') | null;
            /**
             * The button inside an opened card.
             */
            ctaLabel?: string | null;
            /**
             * The link on each card to that service’s own page.
             */
            pageLinkLabel?: string | null;
            /**
             * Pick from Content → Services (each has its own page). Leave empty to show every published service.
             */
            services?: (number | Service)[] | null;
            /**
             * Small add-ons shown as chips under the cards, e.g. “Logo animation”.
             */
            extras?: string[] | null;
            /**
             * Leave anything empty to keep the default shown in grey.
             */
            labels?: {
              featured?: string | null;
              extras?: string | null;
              deckHint?: string | null;
            };
            showWhatsApp?: boolean | null;
            /**
             * Leave anything empty to keep the design’s default.
             */
            style?: {
              background?: string | null;
              text?: string | null;
              accent?: string | null;
              paddingTop?: number | null;
              paddingBottom?: number | null;
              minHeight?: number | null;
              width?: ('default' | 'narrow' | 'wide' | 'full') | null;
              align?: ('default' | 'left' | 'center') | null;
              visibility?: ('all' | 'desktop' | 'mobile') | null;
            };
            hidden?: boolean | null;
            /**
             * Optional. Lets menu links jump here, e.g. “work” for /#work. Letters, numbers and dashes only.
             */
            anchor?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'services';
          }
        | {
            /**
             * The small line above the heading.
             */
            eyebrow?: string | null;
            heading?: string | null;
            items?:
              | {
                  /**
                   * Shown large at the top. Leave empty to show only the quote.
                   */
                  highlight?: string | null;
                  quote: string;
                  name: string;
                  title?: string | null;
                  company?: string | null;
                  logo?: (number | null) | Media;
                  photo?: (number | null) | Media;
                  /**
                   * Star rating from the client, 1–5. Leave empty to show no stars.
                   */
                  rating?: number | null;
                  id?: string | null;
                }[]
              | null;
            /**
             * Leave anything empty to keep the design’s default.
             */
            style?: {
              background?: string | null;
              text?: string | null;
              accent?: string | null;
              paddingTop?: number | null;
              paddingBottom?: number | null;
              minHeight?: number | null;
              width?: ('default' | 'narrow' | 'wide' | 'full') | null;
              align?: ('default' | 'left' | 'center') | null;
              visibility?: ('all' | 'desktop' | 'mobile') | null;
            };
            hidden?: boolean | null;
            /**
             * Optional. Lets menu links jump here, e.g. “work” for /#work. Letters, numbers and dashes only.
             */
            anchor?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonials';
          }
        | {
            /**
             * The small line above the heading.
             */
            eyebrow?: string | null;
            heading?: string | null;
            intro?: string | null;
            rolesLead?: string | null;
            /**
             * Shown as tags, e.g. “startup founder”. Type one and press Enter.
             */
            roles?: string[] | null;
            showAvailability?: boolean | null;
            showSocials?: boolean | null;
            /**
             * Shown when Site settings has a booking link.
             */
            bookLabel?: string | null;
            /**
             * The wording on the enquiry form. Leave anything empty to keep the default shown in grey.
             */
            form?: {
              serviceLabel?: string | null;
              submitLabel?: string | null;
              messagePlaceholder?: string | null;
              successText?: string | null;
              privacyNote?: string | null;
              privacyUrl?: string | null;
            };
            /**
             * Leave anything empty to keep the design’s default.
             */
            style?: {
              background?: string | null;
              text?: string | null;
              accent?: string | null;
              paddingTop?: number | null;
              paddingBottom?: number | null;
              minHeight?: number | null;
              width?: ('default' | 'narrow' | 'wide' | 'full') | null;
              align?: ('default' | 'left' | 'center') | null;
              visibility?: ('all' | 'desktop' | 'mobile') | null;
            };
            hidden?: boolean | null;
            /**
             * Optional. Lets menu links jump here, e.g. “work” for /#work. Letters, numbers and dashes only.
             */
            anchor?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contact';
          }
        | {
            heading?: string | null;
            intro?: string | null;
            showFilters?: boolean | null;
            onlyFeatured?: boolean | null;
            /**
             * Leave anything empty to keep the design’s default.
             */
            style?: {
              background?: string | null;
              text?: string | null;
              accent?: string | null;
              paddingTop?: number | null;
              paddingBottom?: number | null;
              minHeight?: number | null;
              width?: ('default' | 'narrow' | 'wide' | 'full') | null;
              align?: ('default' | 'left' | 'center') | null;
              visibility?: ('all' | 'desktop' | 'mobile') | null;
            };
            hidden?: boolean | null;
            /**
             * Optional. Lets menu links jump here, e.g. “work” for /#work. Letters, numbers and dashes only.
             */
            anchor?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'projectGrid';
          }
        | {
            /**
             * The small line above the heading.
             */
            eyebrow?: string | null;
            heading: string;
            body?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            photo?: (number | null) | Media;
            experience?:
              | {
                  role: string;
                  company?: string | null;
                  years?: string | null;
                  id?: string | null;
                }[]
              | null;
            skills?: string[] | null;
            tools?: string[] | null;
            cv?: (number | null) | Media;
            button?: {
              label?: string | null;
              /**
               * A page (/about), a section (/#contact) or a full URL.
               */
              url?: string | null;
              variant?: ('default' | 'light' | 'dark' | 'accent' | 'outline' | 'ghost') | null;
            };
            /**
             * Leave anything empty to keep the design’s default.
             */
            style?: {
              background?: string | null;
              text?: string | null;
              accent?: string | null;
              paddingTop?: number | null;
              paddingBottom?: number | null;
              minHeight?: number | null;
              width?: ('default' | 'narrow' | 'wide' | 'full') | null;
              align?: ('default' | 'left' | 'center') | null;
              visibility?: ('all' | 'desktop' | 'mobile') | null;
            };
            hidden?: boolean | null;
            /**
             * Optional. Lets menu links jump here, e.g. “work” for /#work. Letters, numbers and dashes only.
             */
            anchor?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'profile';
          }
        | {
            /**
             * The small line above the heading.
             */
            eyebrow?: string | null;
            heading?: string | null;
            body?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            align?: ('left' | 'center') | null;
            /**
             * Leave anything empty to keep the design’s default.
             */
            style?: {
              background?: string | null;
              text?: string | null;
              accent?: string | null;
              paddingTop?: number | null;
              paddingBottom?: number | null;
              minHeight?: number | null;
              width?: ('default' | 'narrow' | 'wide' | 'full') | null;
              align?: ('default' | 'left' | 'center') | null;
              visibility?: ('all' | 'desktop' | 'mobile') | null;
            };
            hidden?: boolean | null;
            /**
             * Optional. Lets menu links jump here, e.g. “work” for /#work. Letters, numbers and dashes only.
             */
            anchor?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            media: number | Media;
            caption?: string | null;
            width?: ('wide' | 'full') | null;
            /**
             * Leave anything empty to keep the design’s default.
             */
            style?: {
              background?: string | null;
              text?: string | null;
              accent?: string | null;
              paddingTop?: number | null;
              paddingBottom?: number | null;
              minHeight?: number | null;
              width?: ('default' | 'narrow' | 'wide' | 'full') | null;
              align?: ('default' | 'left' | 'center') | null;
              visibility?: ('all' | 'desktop' | 'mobile') | null;
            };
            hidden?: boolean | null;
            /**
             * Optional. Lets menu links jump here, e.g. “work” for /#work. Letters, numbers and dashes only.
             */
            anchor?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'mediaSection';
          }
        | {
            heading: string;
            text?: string | null;
            button?: {
              label?: string | null;
              /**
               * A page (/about), a section (/#contact) or a full URL.
               */
              url?: string | null;
              variant?: ('default' | 'light' | 'dark' | 'accent' | 'outline' | 'ghost') | null;
            };
            /**
             * Leave anything empty to keep the design’s default.
             */
            style?: {
              background?: string | null;
              text?: string | null;
              accent?: string | null;
              paddingTop?: number | null;
              paddingBottom?: number | null;
              minHeight?: number | null;
              width?: ('default' | 'narrow' | 'wide' | 'full') | null;
              align?: ('default' | 'left' | 'center') | null;
              visibility?: ('all' | 'desktop' | 'mobile') | null;
            };
            hidden?: boolean | null;
            /**
             * Optional. Lets menu links jump here, e.g. “work” for /#work. Letters, numbers and dashes only.
             */
            anchor?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'ctaBanner';
          }
        | {
            /**
             * The small line above the heading.
             */
            eyebrow?: string | null;
            heading?: string | null;
            items?:
              | {
                  question: string;
                  answer: string;
                  id?: string | null;
                }[]
              | null;
            /**
             * Leave anything empty to keep the design’s default.
             */
            style?: {
              background?: string | null;
              text?: string | null;
              accent?: string | null;
              paddingTop?: number | null;
              paddingBottom?: number | null;
              minHeight?: number | null;
              width?: ('default' | 'narrow' | 'wide' | 'full') | null;
              align?: ('default' | 'left' | 'center') | null;
              visibility?: ('all' | 'desktop' | 'mobile') | null;
            };
            hidden?: boolean | null;
            /**
             * Optional. Lets menu links jump here, e.g. “work” for /#work. Letters, numbers and dashes only.
             */
            anchor?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faq';
          }
        | {
            /**
             * The small line above the heading.
             */
            eyebrow?: string | null;
            heading?: string | null;
            intro?: string | null;
            /**
             * Tools that aren’t on a project yet. The rest come from your projects.
             */
            extra?: string[] | null;
            showCounts?: boolean | null;
            /**
             * Leave anything empty to keep the design’s default.
             */
            style?: {
              background?: string | null;
              text?: string | null;
              accent?: string | null;
              paddingTop?: number | null;
              paddingBottom?: number | null;
              minHeight?: number | null;
              width?: ('default' | 'narrow' | 'wide' | 'full') | null;
              align?: ('default' | 'left' | 'center') | null;
              visibility?: ('all' | 'desktop' | 'mobile') | null;
            };
            hidden?: boolean | null;
            /**
             * Optional. Lets menu links jump here, e.g. “work” for /#work. Letters, numbers and dashes only.
             */
            anchor?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'tools';
          }
        | {
            /**
             * The small line above the heading.
             */
            eyebrow?: string | null;
            heading?: string | null;
            text?: string | null;
            /**
             * An uploaded video file. Or use a YouTube/Vimeo link below instead.
             */
            video?: (number | null) | Media;
            /**
             * Used when there’s no uploaded video.
             */
            link?: string | null;
            /**
             * Shown before it plays. Defaults to the first project cover.
             */
            poster?: (number | null) | Media;
            buttonLabel?: string | null;
            /**
             * Leave anything empty to keep the design’s default.
             */
            style?: {
              background?: string | null;
              text?: string | null;
              accent?: string | null;
              paddingTop?: number | null;
              paddingBottom?: number | null;
              minHeight?: number | null;
              width?: ('default' | 'narrow' | 'wide' | 'full') | null;
              align?: ('default' | 'left' | 'center') | null;
              visibility?: ('all' | 'desktop' | 'mobile') | null;
            };
            hidden?: boolean | null;
            /**
             * Optional. Lets menu links jump here, e.g. “work” for /#work. Letters, numbers and dashes only.
             */
            anchor?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'showreel';
          }
        | {
            /**
             * The small line above the heading.
             */
            eyebrow?: string | null;
            heading?: string | null;
            count?: number | null;
            button?: {
              label?: string | null;
              /**
               * A page (/about), a section (/#contact) or a full URL.
               */
              url?: string | null;
              variant?: ('default' | 'light' | 'dark' | 'accent' | 'outline' | 'ghost') | null;
            };
            /**
             * Leave anything empty to keep the design’s default.
             */
            style?: {
              background?: string | null;
              text?: string | null;
              accent?: string | null;
              paddingTop?: number | null;
              paddingBottom?: number | null;
              minHeight?: number | null;
              width?: ('default' | 'narrow' | 'wide' | 'full') | null;
              align?: ('default' | 'left' | 'center') | null;
              visibility?: ('all' | 'desktop' | 'mobile') | null;
            };
            hidden?: boolean | null;
            /**
             * Optional. Lets menu links jump here, e.g. “work” for /#work. Letters, numbers and dashes only.
             */
            anchor?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'insights';
          }
        | {
            /**
             * The small line above the heading.
             */
            eyebrow?: string | null;
            /**
             * Wrap a word in *asterisks* for the serif accent, e.g. Humphrey *Kibet.*
             */
            name: string;
            role?: string | null;
            intro?: string | null;
            currentLead?: string | null;
            current?: string | null;
            /**
             * Adds the download buttons. Leave empty to hide them.
             */
            cv?: (number | null) | Media;
            cvLabel?: string | null;
            /**
             * The dark card beside your name. Leave the heading empty to hide it.
             */
            card?: {
              kicker?: string | null;
              heading?: string | null;
              text?: string | null;
              topicsLabel?: string | null;
              /**
               * Type one and press Enter.
               */
              topics?: string[] | null;
              /**
               * Shown as outlined chips, e.g. Remote-first, Full-time, Contract.
               */
              workTypes?: string[] | null;
              place?: string | null;
            };
            cardLink?: {
              label?: string | null;
              /**
               * A page (/about), a section (/#contact) or a full URL.
               */
              url?: string | null;
              variant?: ('default' | 'light' | 'dark' | 'accent' | 'outline' | 'ghost') | null;
            };
            /**
             * A row of figures under the intro.
             */
            stats?:
              | {
                  value: string;
                  label: string;
                  id?: string | null;
                }[]
              | null;
            profileHeading?: string | null;
            /**
             * A blank line starts a new paragraph.
             */
            profile?: string | null;
            /**
             * Optional. Set large in the serif italic.
             */
            quote?: string | null;
            pillars?:
              | {
                  title: string;
                  text?: string | null;
                  id?: string | null;
                }[]
              | null;
            xpHeading?: string | null;
            /**
             * Newest first.
             */
            jobs?:
              | {
                  role: string;
                  company: string;
                  dates?: string | null;
                  place?: string | null;
                  mode?: string | null;
                  about?: string | null;
                  /**
                   * Optional. A bold line above the points.
                   */
                  summary?: string | null;
                  /**
                   * What you did and what changed. Type one and press Enter.
                   */
                  points?: string[] | null;
                  linkLabel?: string | null;
                  linkUrl?: string | null;
                  id?: string | null;
                }[]
              | null;
            workHeading?: string | null;
            workIntro?: string | null;
            /**
             * Up to four. Leave empty to show the first featured projects.
             */
            projects?: (number | Project)[] | null;
            workLink?: {
              label?: string | null;
              /**
               * A page (/about), a section (/#contact) or a full URL.
               */
              url?: string | null;
              variant?: ('default' | 'light' | 'dark' | 'accent' | 'outline' | 'ghost') | null;
            };
            skillsHeading?: string | null;
            skillGroups?:
              | {
                  label: string;
                  /**
                   * Type one and press Enter.
                   */
                  items?: string[] | null;
                  id?: string | null;
                }[]
              | null;
            eduHeading?: string | null;
            schools?:
              | {
                  qualification: string;
                  years?: string | null;
                  school: string;
                  place?: string | null;
                  note?: string | null;
                  id?: string | null;
                }[]
              | null;
            certs?:
              | {
                  title: string;
                  year?: string | null;
                  issuer?: string | null;
                  note?: string | null;
                  id?: string | null;
                }[]
              | null;
            closingKicker?: string | null;
            closingHeading?: string | null;
            closingText?: string | null;
            closingLink?: {
              label?: string | null;
              /**
               * A page (/about), a section (/#contact) or a full URL.
               */
              url?: string | null;
              variant?: ('default' | 'light' | 'dark' | 'accent' | 'outline' | 'ghost') | null;
            };
            showEmail?: boolean | null;
            showLinkedIn?: boolean | null;
            /**
             * Leave anything empty to keep the design’s default.
             */
            style?: {
              background?: string | null;
              text?: string | null;
              accent?: string | null;
              paddingTop?: number | null;
              paddingBottom?: number | null;
              minHeight?: number | null;
              width?: ('default' | 'narrow' | 'wide' | 'full') | null;
              align?: ('default' | 'left' | 'center') | null;
              visibility?: ('all' | 'desktop' | 'mobile') | null;
            };
            hidden?: boolean | null;
            /**
             * Optional. Lets menu links jump here, e.g. “work” for /#work. Letters, numbers and dashes only.
             */
            anchor?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'resume';
          }
      )[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Drag rows to set the order projects appear on the site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  _order?: string | null;
  title: string;
  /**
   * One or two sentences. Shown on project cards and in search/social previews.
   */
  summary: string;
  /**
   * The thumbnail and the big image at the top of the case study. Landscape 16:10 works best.
   */
  cover: number | Media;
  /**
   * One or two sentences on your part, shown under the lead image, e.g. “Creative lead: I created the logo and visual identity, and work across social and campaigns.”
   */
  contribution?: string | null;
  /**
   * What the client needed.
   */
  brief?: string | null;
  /**
   * What you did and why.
   */
  approach?: string | null;
  /**
   * What happened after launch. Keep it factual.
   */
  outcome?: string | null;
  /**
   * What you handed over, e.g. Poster templates, Brand guidelines.
   */
  deliverables?: string[] | null;
  /**
   * e.g. Photoshop, Illustrator, Figma.
   */
  tools?: string[] | null;
  /**
   * How long it took, e.g. “3 weeks” or “Ongoing since 2023”.
   */
  timeline?: string | null;
  samples?:
    | {
        file: number | Media;
        title?: string | null;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  layout?:
    | (
        | {
            image: number | Media;
            caption?: string | null;
            width?: ('contained' | 'wide' | 'full') | null;
            /**
             * Optional backdrop colour, e.g. #111111
             */
            background?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'image';
          }
        | {
            images: (number | Media)[];
            columns?: ('2' | '3' | '4') | null;
            aspect?: ('auto' | 'square' | 'portrait' | 'story' | 'landscape') | null;
            width?: ('contained' | 'wide' | 'full') | null;
            caption?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'gallery';
          }
        | {
            heading?: string | null;
            body: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            before: number | Media;
            after: number | Media;
            /**
             * e.g. “Sketch”, “Concept”, “Old logo”.
             */
            beforeLabel?: string | null;
            /**
             * e.g. “Final”, “Printed”, “New logo”.
             */
            afterLabel?: string | null;
            caption?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'beforeAfter';
          }
        | {
            heading?: string | null;
            colours?:
              | {
                  hex: string;
                  name?: string | null;
                  note?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'palette';
          }
        | {
            heading?: string | null;
            fonts?:
              | {
                  family: string;
                  usage?: string | null;
                  /**
                   * Optional image of the typeface in use
                   */
                  specimen?: (number | null) | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'typography';
          }
        | {
            /**
             * Upload an MP4 (plays muted on loop, like a GIF)…
             */
            file?: (number | null) | Media;
            /**
             * …or paste a YouTube / Vimeo link
             */
            embed?: string | null;
            caption?: string | null;
            width?: ('contained' | 'wide' | 'full') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'video';
          }
        | {
            quote: string;
            name?: string | null;
            title?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'quote';
          }
        | {
            heading?: string | null;
            items?:
              | {
                  value: string;
                  label: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'stats';
          }
      )[]
    | null;
  /**
   * Defaults to the project title.
   */
  metaTitle?: string | null;
  /**
   * Defaults to the summary.
   */
  metaDescription?: string | null;
  /**
   * Image shown when the link is shared (1200×630). Defaults to the cover.
   */
  ogImage?: (number | null) | Media;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  /**
   * Show on the homepage
   */
  featured?: boolean | null;
  client: string;
  year: string;
  disciplines: ('social' | 'brand' | 'web' | 'print' | 'packaging' | 'illustration' | 'motion')[];
  /**
   * e.g. Art direction, Layout system
   */
  role?: string[] | null;
  /**
   * The live website, a YouTube/Vimeo video, or a public post. Shows a preview button on the case study.
   */
  liveUrl?: string | null;
  liveType?: ('website' | 'video' | 'post') | null;
  /**
   * Leave empty and the card, its glow and the case study take their colour from the cover. Set a hex (e.g. #F5C400) to use a brand colour instead.
   */
  accent?: string | null;
  /**
   * Small print shown at the end (NDA, placeholder images, etc.)
   */
  note?: string | null;
  /**
   * Up to two real, checkable results for the foot of the project card, e.g. “05” Deliverables and “+120%” Engagement. Leave empty to show the year instead.
   */
  stats?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Every image and video used on the site. Upload big (up to 2560px wide); the site resizes for each screen.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image for screen readers and search engines, e.g. "Matchday poster for Arsenal v Chelsea".
   */
  alt: string;
  caption?: string | null;
  blurDataURL?: string | null;
  prefix?: string | null;
  _objectKey?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Each service has its own page. Drag rows to set the order they appear in.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  _order?: string | null;
  title: string;
  /**
   * Shown on the card and under the title on the page.
   */
  description?: string | null;
  /**
   * Leave empty to hide the price.
   */
  priceFrom?: number | null;
  currency?: ('KES' | 'USD') | null;
  unit?: string | null;
  /**
   * The picture on the service card, under the title on its page, and when the page is shared. Use real work for this service. If empty, the card shows its number instead and the page shows no picture.
   */
  image?: (number | null) | Media;
  /**
   * Under the cover, e.g. “Triad Brands / Brand identity”.
   */
  imageCaption?: string | null;
  /**
   * The bullet points on the card and the page. Type one and press Enter.
   */
  deliverables?: string[] | null;
  /**
   * Shown inverted (dark), with a “Featured” label.
   */
  featured?: boolean | null;
  /**
   * Marks a small, low-risk way to start working together.
   */
  starter?: boolean | null;
  /**
   * A short paragraph: what it is and the problem it solves.
   */
  intro?: string | null;
  /**
   * Who it suits, e.g. “Startups launching”.
   */
  goodFor?: string[] | null;
  timeline?: string | null;
  steps?:
    | {
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Projects shown on the page as examples of this service.
   */
  projects?: (number | Project)[] | null;
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Defaults to the service title.
   */
  metaTitle?: string | null;
  /**
   * Defaults to the one-line summary.
   */
  metaDescription?: string | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Short articles and design notes. They appear at /insights and in the Insights section.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * One or two sentences for the card and search/social previews.
   */
  excerpt: string;
  /**
   * Landscape 16:10 works best. Without one, the card shows a coloured panel with the title.
   */
  cover?: (number | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  publishedAt: string;
  /**
   * e.g. Branding, Process
   */
  tags?: string[] | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  /**
   * Defaults to the title.
   */
  metaTitle?: string | null;
  /**
   * Defaults to the excerpt.
   */
  metaDescription?: string | null;
  /**
   * Shown when the link is shared (1200×630). Defaults to the cover.
   */
  ogImage?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries".
 */
export interface Inquiry {
  id: number;
  name: string;
  email: string;
  service?: string | null;
  budget?: string | null;
  /**
   * When they need it, from the brief builder.
   */
  timeline?: string | null;
  brandStage?: ('new' | 'rebrand' | 'refresh') | null;
  whatsapp?: string | null;
  logoWording?: string | null;
  keep?: string | null;
  message: string;
  status?: ('new' | 'replied' | 'archived') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  /**
   * Admins can add, remove and change other people’s accounts. Editors can only edit content and their own account.
   */
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'inquiries';
        value: number | Inquiry;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  sections?:
    | T
    | {
        hero?:
          | T
          | {
              trustedText?: T;
              headline?: T;
              intro?: T;
              ctaText?: T;
              button?:
                | T
                | {
                    label?: T;
                    url?: T;
                    variant?: T;
                  };
              clientsLabel?: T;
              clients?:
                | T
                | {
                    name?: T;
                    url?: T;
                    id?: T;
                  };
              projects?: T;
              style?:
                | T
                | {
                    background?: T;
                    text?: T;
                    accent?: T;
                    paddingTop?: T;
                    paddingBottom?: T;
                    minHeight?: T;
                    width?: T;
                    align?: T;
                    visibility?: T;
                  };
              hidden?: T;
              anchor?: T;
              id?: T;
              blockName?: T;
            };
        workShowcase?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              intro?: T;
              layout?: T;
              projects?: T;
              extraImages?: T;
              showWall?: T;
              link?:
                | T
                | {
                    label?: T;
                    url?: T;
                    variant?: T;
                  };
              style?:
                | T
                | {
                    background?: T;
                    text?: T;
                    accent?: T;
                    paddingTop?: T;
                    paddingBottom?: T;
                    minHeight?: T;
                    width?: T;
                    align?: T;
                    visibility?: T;
                  };
              hidden?: T;
              anchor?: T;
              id?: T;
              blockName?: T;
            };
        aboutBanner?:
          | T
          | {
              layout?: T;
              eyebrow?: T;
              role?: T;
              tabs?:
                | T
                | {
                    label?: T;
                    heading?: T;
                    text?: T;
                    rows?:
                      | T
                      | {
                          value?: T;
                          label?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              greeting?: T;
              heading?: T;
              photo?: T;
              moodPhoto?: T;
              stickers?: T;
              caption?: T;
              intro?: T;
              expertise?: T;
              servicesHeading?: T;
              services?: T;
              cta?:
                | T
                | {
                    label?: T;
                    url?: T;
                    variant?: T;
                  };
              stats?:
                | T
                | {
                    value?: T;
                    label?: T;
                    id?: T;
                  };
              bigName?: T;
              link?:
                | T
                | {
                    label?: T;
                    url?: T;
                    variant?: T;
                  };
              style?:
                | T
                | {
                    background?: T;
                    text?: T;
                    accent?: T;
                    paddingTop?: T;
                    paddingBottom?: T;
                    minHeight?: T;
                    width?: T;
                    align?: T;
                    visibility?: T;
                  };
              hidden?: T;
              anchor?: T;
              id?: T;
              blockName?: T;
            };
        audience?:
          | T
          | {
              heading?: T;
              lead?: T;
              roles?: T;
              style?:
                | T
                | {
                    background?: T;
                    text?: T;
                    accent?: T;
                    paddingTop?: T;
                    paddingBottom?: T;
                    minHeight?: T;
                    width?: T;
                    align?: T;
                    visibility?: T;
                  };
              hidden?: T;
              anchor?: T;
              id?: T;
              blockName?: T;
            };
        process?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              lead?: T;
              layout?: T;
              steps?:
                | T
                | {
                    title?: T;
                    icon?: T;
                    duration?: T;
                    description?: T;
                    points?: T;
                    image?: T;
                    id?: T;
                  };
              style?:
                | T
                | {
                    background?: T;
                    text?: T;
                    accent?: T;
                    paddingTop?: T;
                    paddingBottom?: T;
                    minHeight?: T;
                    width?: T;
                    align?: T;
                    visibility?: T;
                  };
              hidden?: T;
              anchor?: T;
              id?: T;
              blockName?: T;
            };
        services?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              intro?: T;
              layout?: T;
              ctaLabel?: T;
              pageLinkLabel?: T;
              services?: T;
              extras?: T;
              labels?:
                | T
                | {
                    featured?: T;
                    extras?: T;
                    deckHint?: T;
                  };
              showWhatsApp?: T;
              style?:
                | T
                | {
                    background?: T;
                    text?: T;
                    accent?: T;
                    paddingTop?: T;
                    paddingBottom?: T;
                    minHeight?: T;
                    width?: T;
                    align?: T;
                    visibility?: T;
                  };
              hidden?: T;
              anchor?: T;
              id?: T;
              blockName?: T;
            };
        testimonials?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              items?:
                | T
                | {
                    highlight?: T;
                    quote?: T;
                    name?: T;
                    title?: T;
                    company?: T;
                    logo?: T;
                    photo?: T;
                    rating?: T;
                    id?: T;
                  };
              style?:
                | T
                | {
                    background?: T;
                    text?: T;
                    accent?: T;
                    paddingTop?: T;
                    paddingBottom?: T;
                    minHeight?: T;
                    width?: T;
                    align?: T;
                    visibility?: T;
                  };
              hidden?: T;
              anchor?: T;
              id?: T;
              blockName?: T;
            };
        contact?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              intro?: T;
              rolesLead?: T;
              roles?: T;
              showAvailability?: T;
              showSocials?: T;
              bookLabel?: T;
              form?:
                | T
                | {
                    serviceLabel?: T;
                    submitLabel?: T;
                    messagePlaceholder?: T;
                    successText?: T;
                    privacyNote?: T;
                    privacyUrl?: T;
                  };
              style?:
                | T
                | {
                    background?: T;
                    text?: T;
                    accent?: T;
                    paddingTop?: T;
                    paddingBottom?: T;
                    minHeight?: T;
                    width?: T;
                    align?: T;
                    visibility?: T;
                  };
              hidden?: T;
              anchor?: T;
              id?: T;
              blockName?: T;
            };
        projectGrid?:
          | T
          | {
              heading?: T;
              intro?: T;
              showFilters?: T;
              onlyFeatured?: T;
              style?:
                | T
                | {
                    background?: T;
                    text?: T;
                    accent?: T;
                    paddingTop?: T;
                    paddingBottom?: T;
                    minHeight?: T;
                    width?: T;
                    align?: T;
                    visibility?: T;
                  };
              hidden?: T;
              anchor?: T;
              id?: T;
              blockName?: T;
            };
        profile?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              body?: T;
              photo?: T;
              experience?:
                | T
                | {
                    role?: T;
                    company?: T;
                    years?: T;
                    id?: T;
                  };
              skills?: T;
              tools?: T;
              cv?: T;
              button?:
                | T
                | {
                    label?: T;
                    url?: T;
                    variant?: T;
                  };
              style?:
                | T
                | {
                    background?: T;
                    text?: T;
                    accent?: T;
                    paddingTop?: T;
                    paddingBottom?: T;
                    minHeight?: T;
                    width?: T;
                    align?: T;
                    visibility?: T;
                  };
              hidden?: T;
              anchor?: T;
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              body?: T;
              align?: T;
              style?:
                | T
                | {
                    background?: T;
                    text?: T;
                    accent?: T;
                    paddingTop?: T;
                    paddingBottom?: T;
                    minHeight?: T;
                    width?: T;
                    align?: T;
                    visibility?: T;
                  };
              hidden?: T;
              anchor?: T;
              id?: T;
              blockName?: T;
            };
        mediaSection?:
          | T
          | {
              media?: T;
              caption?: T;
              width?: T;
              style?:
                | T
                | {
                    background?: T;
                    text?: T;
                    accent?: T;
                    paddingTop?: T;
                    paddingBottom?: T;
                    minHeight?: T;
                    width?: T;
                    align?: T;
                    visibility?: T;
                  };
              hidden?: T;
              anchor?: T;
              id?: T;
              blockName?: T;
            };
        ctaBanner?:
          | T
          | {
              heading?: T;
              text?: T;
              button?:
                | T
                | {
                    label?: T;
                    url?: T;
                    variant?: T;
                  };
              style?:
                | T
                | {
                    background?: T;
                    text?: T;
                    accent?: T;
                    paddingTop?: T;
                    paddingBottom?: T;
                    minHeight?: T;
                    width?: T;
                    align?: T;
                    visibility?: T;
                  };
              hidden?: T;
              anchor?: T;
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              style?:
                | T
                | {
                    background?: T;
                    text?: T;
                    accent?: T;
                    paddingTop?: T;
                    paddingBottom?: T;
                    minHeight?: T;
                    width?: T;
                    align?: T;
                    visibility?: T;
                  };
              hidden?: T;
              anchor?: T;
              id?: T;
              blockName?: T;
            };
        tools?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              intro?: T;
              extra?: T;
              showCounts?: T;
              style?:
                | T
                | {
                    background?: T;
                    text?: T;
                    accent?: T;
                    paddingTop?: T;
                    paddingBottom?: T;
                    minHeight?: T;
                    width?: T;
                    align?: T;
                    visibility?: T;
                  };
              hidden?: T;
              anchor?: T;
              id?: T;
              blockName?: T;
            };
        showreel?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              text?: T;
              video?: T;
              link?: T;
              poster?: T;
              buttonLabel?: T;
              style?:
                | T
                | {
                    background?: T;
                    text?: T;
                    accent?: T;
                    paddingTop?: T;
                    paddingBottom?: T;
                    minHeight?: T;
                    width?: T;
                    align?: T;
                    visibility?: T;
                  };
              hidden?: T;
              anchor?: T;
              id?: T;
              blockName?: T;
            };
        insights?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              count?: T;
              button?:
                | T
                | {
                    label?: T;
                    url?: T;
                    variant?: T;
                  };
              style?:
                | T
                | {
                    background?: T;
                    text?: T;
                    accent?: T;
                    paddingTop?: T;
                    paddingBottom?: T;
                    minHeight?: T;
                    width?: T;
                    align?: T;
                    visibility?: T;
                  };
              hidden?: T;
              anchor?: T;
              id?: T;
              blockName?: T;
            };
        resume?:
          | T
          | {
              eyebrow?: T;
              name?: T;
              role?: T;
              intro?: T;
              currentLead?: T;
              current?: T;
              cv?: T;
              cvLabel?: T;
              card?:
                | T
                | {
                    kicker?: T;
                    heading?: T;
                    text?: T;
                    topicsLabel?: T;
                    topics?: T;
                    workTypes?: T;
                    place?: T;
                  };
              cardLink?:
                | T
                | {
                    label?: T;
                    url?: T;
                    variant?: T;
                  };
              stats?:
                | T
                | {
                    value?: T;
                    label?: T;
                    id?: T;
                  };
              profileHeading?: T;
              profile?: T;
              quote?: T;
              pillars?:
                | T
                | {
                    title?: T;
                    text?: T;
                    id?: T;
                  };
              xpHeading?: T;
              jobs?:
                | T
                | {
                    role?: T;
                    company?: T;
                    dates?: T;
                    place?: T;
                    mode?: T;
                    about?: T;
                    summary?: T;
                    points?: T;
                    linkLabel?: T;
                    linkUrl?: T;
                    id?: T;
                  };
              workHeading?: T;
              workIntro?: T;
              projects?: T;
              workLink?:
                | T
                | {
                    label?: T;
                    url?: T;
                    variant?: T;
                  };
              skillsHeading?: T;
              skillGroups?:
                | T
                | {
                    label?: T;
                    items?: T;
                    id?: T;
                  };
              eduHeading?: T;
              schools?:
                | T
                | {
                    qualification?: T;
                    years?: T;
                    school?: T;
                    place?: T;
                    note?: T;
                    id?: T;
                  };
              certs?:
                | T
                | {
                    title?: T;
                    year?: T;
                    issuer?: T;
                    note?: T;
                    id?: T;
                  };
              closingKicker?: T;
              closingHeading?: T;
              closingText?: T;
              closingLink?:
                | T
                | {
                    label?: T;
                    url?: T;
                    variant?: T;
                  };
              showEmail?: T;
              showLinkedIn?: T;
              style?:
                | T
                | {
                    background?: T;
                    text?: T;
                    accent?: T;
                    paddingTop?: T;
                    paddingBottom?: T;
                    minHeight?: T;
                    width?: T;
                    align?: T;
                    visibility?: T;
                  };
              hidden?: T;
              anchor?: T;
              id?: T;
              blockName?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  _order?: T;
  title?: T;
  summary?: T;
  cover?: T;
  contribution?: T;
  brief?: T;
  approach?: T;
  outcome?: T;
  deliverables?: T;
  tools?: T;
  timeline?: T;
  samples?:
    | T
    | {
        file?: T;
        title?: T;
        note?: T;
        id?: T;
      };
  layout?:
    | T
    | {
        image?:
          | T
          | {
              image?: T;
              caption?: T;
              width?: T;
              background?: T;
              id?: T;
              blockName?: T;
            };
        gallery?:
          | T
          | {
              images?: T;
              columns?: T;
              aspect?: T;
              width?: T;
              caption?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              heading?: T;
              body?: T;
              id?: T;
              blockName?: T;
            };
        beforeAfter?:
          | T
          | {
              before?: T;
              after?: T;
              beforeLabel?: T;
              afterLabel?: T;
              caption?: T;
              id?: T;
              blockName?: T;
            };
        palette?:
          | T
          | {
              heading?: T;
              colours?:
                | T
                | {
                    hex?: T;
                    name?: T;
                    note?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        typography?:
          | T
          | {
              heading?: T;
              fonts?:
                | T
                | {
                    family?: T;
                    usage?: T;
                    specimen?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        video?:
          | T
          | {
              file?: T;
              embed?: T;
              caption?: T;
              width?: T;
              id?: T;
              blockName?: T;
            };
        quote?:
          | T
          | {
              quote?: T;
              name?: T;
              title?: T;
              id?: T;
              blockName?: T;
            };
        stats?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    value?: T;
                    label?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  metaTitle?: T;
  metaDescription?: T;
  ogImage?: T;
  generateSlug?: T;
  slug?: T;
  featured?: T;
  client?: T;
  year?: T;
  disciplines?: T;
  role?: T;
  liveUrl?: T;
  liveType?: T;
  accent?: T;
  note?: T;
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  _order?: T;
  title?: T;
  description?: T;
  priceFrom?: T;
  currency?: T;
  unit?: T;
  image?: T;
  imageCaption?: T;
  deliverables?: T;
  featured?: T;
  starter?: T;
  intro?: T;
  goodFor?: T;
  timeline?: T;
  steps?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  projects?: T;
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  metaTitle?: T;
  metaDescription?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  excerpt?: T;
  cover?: T;
  content?: T;
  publishedAt?: T;
  tags?: T;
  generateSlug?: T;
  slug?: T;
  metaTitle?: T;
  metaDescription?: T;
  ogImage?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  blurDataURL?: T;
  prefix?: T;
  _objectKey?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries_select".
 */
export interface InquiriesSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  service?: T;
  budget?: T;
  timeline?: T;
  brandStage?: T;
  whatsapp?: T;
  logoWording?: T;
  keep?: T;
  message?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * The floating bar at the top of every page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  /**
   * Links to sections (/#work) highlight while that section is on screen.
   */
  menu?:
    | {
        label: string;
        /**
         * A page (/about), a section (/#work) or a full URL.
         */
        url: string;
        id?: string | null;
      }[]
    | null;
  quoteButton: {
    show?: boolean | null;
    label: string;
    url: string;
  };
  /**
   * The text comes from Site settings → Availability.
   */
  showAvailability?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The footer at the bottom of every page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  /**
   * Leave empty to use Site settings → Name.
   */
  title?: string | null;
  /**
   * Leave empty to use Site settings → Tagline.
   */
  tagline?: string | null;
  showAvailability?: boolean | null;
  showSocials?: boolean | null;
  /**
   * The dark band at the top of the footer.
   */
  cta?: {
    show?: boolean | null;
    heading?: string | null;
    text?: string | null;
    buttonLabel?: string | null;
    /**
     * A page, a section (/#contact), a booking link or mailto:
     */
    buttonUrl?: string | null;
  };
  /**
   * {year} and {name} are filled in automatically.
   */
  copyright?: string | null;
  /**
   * Who made the site, shown as a link on the last line. When the name already appears in the copyright text, that part becomes the link; otherwise "Site by …" is added.
   */
  credit?: {
    label?: string | null;
    /**
     * Their website or profile (https://…). Opens in a new tab.
     */
    url?: string | null;
  };
  /**
   * Shown beside the copyright, e.g. Terms → /terms. The pages themselves are in Pages; link only to ones that exist.
   */
  legal?:
    | {
        label: string;
        /**
         * A page (/about), a section (/#work) or a full URL.
         */
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Small print after the copyright line.
   */
  note?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Colours, fonts, buttons, corners and spacing for the whole site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "theme".
 */
export interface Theme {
  id: number;
  /**
   * The page in dark mode, and dark bands in either mode.
   */
  background?: string | null;
  /**
   * Cards and panels in dark mode.
   */
  surface?: string | null;
  text?: string | null;
  /**
   * Paragraphs and labels in dark mode.
   */
  mutedText?: string | null;
  /**
   * The serif accent words, dots, numbers and small highlights, in both light and dark mode.
   */
  accent?: string | null;
  /**
   * Gradients and small details.
   */
  accent2?: string | null;
  /**
   * The page in light mode (the default).
   */
  lightBackground?: string | null;
  lightSurface?: string | null;
  lightText?: string | null;
  glow?: boolean | null;
  headingFont?:
    | (
        | 'Geist'
        | 'Inter'
        | 'Manrope'
        | 'DM Sans'
        | 'Space Grotesk'
        | 'Plus Jakarta Sans'
        | 'Sora'
        | 'Outfit'
        | 'Instrument Serif'
        | 'Playfair Display'
        | 'Fraunces'
        | 'DM Serif Display'
      )
    | null;
  bodyFont?:
    | (
        | 'Geist'
        | 'Inter'
        | 'Manrope'
        | 'DM Sans'
        | 'Space Grotesk'
        | 'Plus Jakarta Sans'
        | 'Sora'
        | 'Outfit'
        | 'Instrument Serif'
        | 'Playfair Display'
        | 'Fraunces'
        | 'DM Serif Display'
      )
    | null;
  headingWeight?: ('300' | '400' | '500' | '600' | '700') | null;
  headingTracking?: number | null;
  baseSize?: number | null;
  buttonBackground?: string | null;
  buttonText?: string | null;
  buttonDarkBackground?: string | null;
  buttonShape?: ('pill' | 'rounded' | 'square') | null;
  buttonHeight?: number | null;
  /**
   * 100% is the current look; 0 is square corners.
   */
  radius?: number | null;
  spacing?: number | null;
  container?: number | null;
  motion?: ('full' | 'subtle' | 'off') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site".
 */
export interface Site {
  id: number;
  name: string;
  studio?: string | null;
  /**
   * e.g. Graphic designer & social media creative
   */
  role: string;
  /**
   * One short line repeated across the site: under the hero, on the About portrait and in search results, e.g. “A little logic. A lot of imagination.”
   */
  tagline?: string | null;
  location?: string | null;
  /**
   * Shown in the footer and contact section, e.g. "Booking projects for October"
   */
  availability?: string | null;
  email: string;
  /**
   * International format, e.g. +254 720 949 086
   */
  phone?: string | null;
  /**
   * Show a WhatsApp button using the phone number above
   */
  whatsapp?: boolean | null;
  /**
   * Your Cal.com, Calendly or Google booking page. When set, a “Book a call” button appears beside the contact form.
   */
  bookingUrl?: string | null;
  /**
   * Only profiles with a full URL are shown.
   */
  socials?:
    | {
        platform: 'instagram' | 'behance' | 'dribbble' | 'linkedin' | 'x' | 'facebook' | 'tiktok';
        url: string;
        id?: string | null;
      }[]
    | null;
  metaDescription?: string | null;
  /**
   * Default image when a page is shared (1200×630)
   */
  ogImage?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  menu?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  quoteButton?:
    | T
    | {
        show?: T;
        label?: T;
        url?: T;
      };
  showAvailability?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  title?: T;
  tagline?: T;
  showAvailability?: T;
  showSocials?: T;
  cta?:
    | T
    | {
        show?: T;
        heading?: T;
        text?: T;
        buttonLabel?: T;
        buttonUrl?: T;
      };
  copyright?: T;
  credit?:
    | T
    | {
        label?: T;
        url?: T;
      };
  legal?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  note?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "theme_select".
 */
export interface ThemeSelect<T extends boolean = true> {
  background?: T;
  surface?: T;
  text?: T;
  mutedText?: T;
  accent?: T;
  accent2?: T;
  lightBackground?: T;
  lightSurface?: T;
  lightText?: T;
  glow?: T;
  headingFont?: T;
  bodyFont?: T;
  headingWeight?: T;
  headingTracking?: T;
  baseSize?: T;
  buttonBackground?: T;
  buttonText?: T;
  buttonDarkBackground?: T;
  buttonShape?: T;
  buttonHeight?: T;
  radius?: T;
  spacing?: T;
  container?: T;
  motion?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site_select".
 */
export interface SiteSelect<T extends boolean = true> {
  name?: T;
  studio?: T;
  role?: T;
  tagline?: T;
  location?: T;
  availability?: T;
  email?: T;
  phone?: T;
  whatsapp?: T;
  bookingUrl?: T;
  socials?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  metaDescription?: T;
  ogImage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}