import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   CREATE TYPE "public"."enum_pages_blocks_hero_button_variant" AS ENUM('default', 'light', 'dark', 'accent', 'outline', 'ghost');
  CREATE TYPE "public"."enum_pages_blocks_hero_style_width" AS ENUM('default', 'narrow', 'wide', 'full');
  CREATE TYPE "public"."enum_pages_blocks_hero_style_align" AS ENUM('default', 'left', 'center');
  CREATE TYPE "public"."enum_pages_blocks_hero_style_visibility" AS ENUM('all', 'desktop', 'mobile');
  CREATE TYPE "public"."enum_pages_blocks_work_showcase_link_variant" AS ENUM('default', 'light', 'dark', 'accent', 'outline', 'ghost');
  CREATE TYPE "public"."enum_pages_blocks_work_showcase_style_width" AS ENUM('default', 'narrow', 'wide', 'full');
  CREATE TYPE "public"."enum_pages_blocks_work_showcase_style_align" AS ENUM('default', 'left', 'center');
  CREATE TYPE "public"."enum_pages_blocks_work_showcase_style_visibility" AS ENUM('all', 'desktop', 'mobile');
  CREATE TYPE "public"."enum_pages_blocks_about_banner_link_variant" AS ENUM('default', 'light', 'dark', 'accent', 'outline', 'ghost');
  CREATE TYPE "public"."enum_pages_blocks_about_banner_style_width" AS ENUM('default', 'narrow', 'wide', 'full');
  CREATE TYPE "public"."enum_pages_blocks_about_banner_style_align" AS ENUM('default', 'left', 'center');
  CREATE TYPE "public"."enum_pages_blocks_about_banner_style_visibility" AS ENUM('all', 'desktop', 'mobile');
  CREATE TYPE "public"."enum_pages_blocks_audience_style_width" AS ENUM('default', 'narrow', 'wide', 'full');
  CREATE TYPE "public"."enum_pages_blocks_audience_style_align" AS ENUM('default', 'left', 'center');
  CREATE TYPE "public"."enum_pages_blocks_audience_style_visibility" AS ENUM('all', 'desktop', 'mobile');
  CREATE TYPE "public"."enum_pages_blocks_process_style_width" AS ENUM('default', 'narrow', 'wide', 'full');
  CREATE TYPE "public"."enum_pages_blocks_process_style_align" AS ENUM('default', 'left', 'center');
  CREATE TYPE "public"."enum_pages_blocks_process_style_visibility" AS ENUM('all', 'desktop', 'mobile');
  CREATE TYPE "public"."enum_pages_blocks_services_style_width" AS ENUM('default', 'narrow', 'wide', 'full');
  CREATE TYPE "public"."enum_pages_blocks_services_style_align" AS ENUM('default', 'left', 'center');
  CREATE TYPE "public"."enum_pages_blocks_services_style_visibility" AS ENUM('all', 'desktop', 'mobile');
  CREATE TYPE "public"."enum_pages_blocks_testimonials_style_width" AS ENUM('default', 'narrow', 'wide', 'full');
  CREATE TYPE "public"."enum_pages_blocks_testimonials_style_align" AS ENUM('default', 'left', 'center');
  CREATE TYPE "public"."enum_pages_blocks_testimonials_style_visibility" AS ENUM('all', 'desktop', 'mobile');
  CREATE TYPE "public"."enum_pages_blocks_contact_style_width" AS ENUM('default', 'narrow', 'wide', 'full');
  CREATE TYPE "public"."enum_pages_blocks_contact_style_align" AS ENUM('default', 'left', 'center');
  CREATE TYPE "public"."enum_pages_blocks_contact_style_visibility" AS ENUM('all', 'desktop', 'mobile');
  CREATE TYPE "public"."enum_pages_blocks_project_grid_style_width" AS ENUM('default', 'narrow', 'wide', 'full');
  CREATE TYPE "public"."enum_pages_blocks_project_grid_style_align" AS ENUM('default', 'left', 'center');
  CREATE TYPE "public"."enum_pages_blocks_project_grid_style_visibility" AS ENUM('all', 'desktop', 'mobile');
  CREATE TYPE "public"."enum_pages_blocks_profile_button_variant" AS ENUM('default', 'light', 'dark', 'accent', 'outline', 'ghost');
  CREATE TYPE "public"."enum_pages_blocks_profile_style_width" AS ENUM('default', 'narrow', 'wide', 'full');
  CREATE TYPE "public"."enum_pages_blocks_profile_style_align" AS ENUM('default', 'left', 'center');
  CREATE TYPE "public"."enum_pages_blocks_profile_style_visibility" AS ENUM('all', 'desktop', 'mobile');
  CREATE TYPE "public"."enum_pages_blocks_rich_text_style_width" AS ENUM('default', 'narrow', 'wide', 'full');
  CREATE TYPE "public"."enum_pages_blocks_rich_text_style_align" AS ENUM('default', 'left', 'center');
  CREATE TYPE "public"."enum_pages_blocks_rich_text_style_visibility" AS ENUM('all', 'desktop', 'mobile');
  CREATE TYPE "public"."enum_pages_blocks_media_section_style_width" AS ENUM('default', 'narrow', 'wide', 'full');
  CREATE TYPE "public"."enum_pages_blocks_media_section_style_align" AS ENUM('default', 'left', 'center');
  CREATE TYPE "public"."enum_pages_blocks_media_section_style_visibility" AS ENUM('all', 'desktop', 'mobile');
  CREATE TYPE "public"."enum_pages_blocks_cta_banner_button_variant" AS ENUM('default', 'light', 'dark', 'accent', 'outline', 'ghost');
  CREATE TYPE "public"."enum_pages_blocks_cta_banner_style_width" AS ENUM('default', 'narrow', 'wide', 'full');
  CREATE TYPE "public"."enum_pages_blocks_cta_banner_style_align" AS ENUM('default', 'left', 'center');
  CREATE TYPE "public"."enum_pages_blocks_cta_banner_style_visibility" AS ENUM('all', 'desktop', 'mobile');
  CREATE TYPE "public"."enum_pages_blocks_faq_style_width" AS ENUM('default', 'narrow', 'wide', 'full');
  CREATE TYPE "public"."enum_pages_blocks_faq_style_align" AS ENUM('default', 'left', 'center');
  CREATE TYPE "public"."enum_pages_blocks_faq_style_visibility" AS ENUM('all', 'desktop', 'mobile');
  CREATE TYPE "public"."enum__pages_v_blocks_hero_button_variant" AS ENUM('default', 'light', 'dark', 'accent', 'outline', 'ghost');
  CREATE TYPE "public"."enum__pages_v_blocks_hero_style_width" AS ENUM('default', 'narrow', 'wide', 'full');
  CREATE TYPE "public"."enum__pages_v_blocks_hero_style_align" AS ENUM('default', 'left', 'center');
  CREATE TYPE "public"."enum__pages_v_blocks_hero_style_visibility" AS ENUM('all', 'desktop', 'mobile');
  CREATE TYPE "public"."enum__pages_v_blocks_work_showcase_link_variant" AS ENUM('default', 'light', 'dark', 'accent', 'outline', 'ghost');
  CREATE TYPE "public"."enum__pages_v_blocks_work_showcase_style_width" AS ENUM('default', 'narrow', 'wide', 'full');
  CREATE TYPE "public"."enum__pages_v_blocks_work_showcase_style_align" AS ENUM('default', 'left', 'center');
  CREATE TYPE "public"."enum__pages_v_blocks_work_showcase_style_visibility" AS ENUM('all', 'desktop', 'mobile');
  CREATE TYPE "public"."enum__pages_v_blocks_about_banner_link_variant" AS ENUM('default', 'light', 'dark', 'accent', 'outline', 'ghost');
  CREATE TYPE "public"."enum__pages_v_blocks_about_banner_style_width" AS ENUM('default', 'narrow', 'wide', 'full');
  CREATE TYPE "public"."enum__pages_v_blocks_about_banner_style_align" AS ENUM('default', 'left', 'center');
  CREATE TYPE "public"."enum__pages_v_blocks_about_banner_style_visibility" AS ENUM('all', 'desktop', 'mobile');
  CREATE TYPE "public"."enum__pages_v_blocks_audience_style_width" AS ENUM('default', 'narrow', 'wide', 'full');
  CREATE TYPE "public"."enum__pages_v_blocks_audience_style_align" AS ENUM('default', 'left', 'center');
  CREATE TYPE "public"."enum__pages_v_blocks_audience_style_visibility" AS ENUM('all', 'desktop', 'mobile');
  CREATE TYPE "public"."enum__pages_v_blocks_process_style_width" AS ENUM('default', 'narrow', 'wide', 'full');
  CREATE TYPE "public"."enum__pages_v_blocks_process_style_align" AS ENUM('default', 'left', 'center');
  CREATE TYPE "public"."enum__pages_v_blocks_process_style_visibility" AS ENUM('all', 'desktop', 'mobile');
  CREATE TYPE "public"."enum__pages_v_blocks_services_style_width" AS ENUM('default', 'narrow', 'wide', 'full');
  CREATE TYPE "public"."enum__pages_v_blocks_services_style_align" AS ENUM('default', 'left', 'center');
  CREATE TYPE "public"."enum__pages_v_blocks_services_style_visibility" AS ENUM('all', 'desktop', 'mobile');
  CREATE TYPE "public"."enum__pages_v_blocks_testimonials_style_width" AS ENUM('default', 'narrow', 'wide', 'full');
  CREATE TYPE "public"."enum__pages_v_blocks_testimonials_style_align" AS ENUM('default', 'left', 'center');
  CREATE TYPE "public"."enum__pages_v_blocks_testimonials_style_visibility" AS ENUM('all', 'desktop', 'mobile');
  CREATE TYPE "public"."enum__pages_v_blocks_contact_style_width" AS ENUM('default', 'narrow', 'wide', 'full');
  CREATE TYPE "public"."enum__pages_v_blocks_contact_style_align" AS ENUM('default', 'left', 'center');
  CREATE TYPE "public"."enum__pages_v_blocks_contact_style_visibility" AS ENUM('all', 'desktop', 'mobile');
  CREATE TYPE "public"."enum__pages_v_blocks_project_grid_style_width" AS ENUM('default', 'narrow', 'wide', 'full');
  CREATE TYPE "public"."enum__pages_v_blocks_project_grid_style_align" AS ENUM('default', 'left', 'center');
  CREATE TYPE "public"."enum__pages_v_blocks_project_grid_style_visibility" AS ENUM('all', 'desktop', 'mobile');
  CREATE TYPE "public"."enum__pages_v_blocks_profile_button_variant" AS ENUM('default', 'light', 'dark', 'accent', 'outline', 'ghost');
  CREATE TYPE "public"."enum__pages_v_blocks_profile_style_width" AS ENUM('default', 'narrow', 'wide', 'full');
  CREATE TYPE "public"."enum__pages_v_blocks_profile_style_align" AS ENUM('default', 'left', 'center');
  CREATE TYPE "public"."enum__pages_v_blocks_profile_style_visibility" AS ENUM('all', 'desktop', 'mobile');
  CREATE TYPE "public"."enum__pages_v_blocks_rich_text_style_width" AS ENUM('default', 'narrow', 'wide', 'full');
  CREATE TYPE "public"."enum__pages_v_blocks_rich_text_style_align" AS ENUM('default', 'left', 'center');
  CREATE TYPE "public"."enum__pages_v_blocks_rich_text_style_visibility" AS ENUM('all', 'desktop', 'mobile');
  CREATE TYPE "public"."enum__pages_v_blocks_media_section_style_width" AS ENUM('default', 'narrow', 'wide', 'full');
  CREATE TYPE "public"."enum__pages_v_blocks_media_section_style_align" AS ENUM('default', 'left', 'center');
  CREATE TYPE "public"."enum__pages_v_blocks_media_section_style_visibility" AS ENUM('all', 'desktop', 'mobile');
  CREATE TYPE "public"."enum__pages_v_blocks_cta_banner_button_variant" AS ENUM('default', 'light', 'dark', 'accent', 'outline', 'ghost');
  CREATE TYPE "public"."enum__pages_v_blocks_cta_banner_style_width" AS ENUM('default', 'narrow', 'wide', 'full');
  CREATE TYPE "public"."enum__pages_v_blocks_cta_banner_style_align" AS ENUM('default', 'left', 'center');
  CREATE TYPE "public"."enum__pages_v_blocks_cta_banner_style_visibility" AS ENUM('all', 'desktop', 'mobile');
  CREATE TYPE "public"."enum__pages_v_blocks_faq_style_width" AS ENUM('default', 'narrow', 'wide', 'full');
  CREATE TYPE "public"."enum__pages_v_blocks_faq_style_align" AS ENUM('default', 'left', 'center');
  CREATE TYPE "public"."enum__pages_v_blocks_faq_style_visibility" AS ENUM('all', 'desktop', 'mobile');
  CREATE TYPE "public"."enum_theme_heading_font" AS ENUM('Geist', 'Inter', 'Manrope', 'DM Sans', 'Space Grotesk', 'Plus Jakarta Sans', 'Sora', 'Outfit', 'Instrument Serif', 'Playfair Display', 'Fraunces', 'DM Serif Display');
  CREATE TYPE "public"."enum_theme_body_font" AS ENUM('Geist', 'Inter', 'Manrope', 'DM Sans', 'Space Grotesk', 'Plus Jakarta Sans', 'Sora', 'Outfit', 'Instrument Serif', 'Playfair Display', 'Fraunces', 'DM Serif Display');
  CREATE TYPE "public"."enum_theme_heading_weight" AS ENUM('300', '400', '500', '600', '700');
  CREATE TYPE "public"."enum_theme_button_shape" AS ENUM('pill', 'rounded', 'square');
  CREATE TYPE "public"."enum_theme_motion" AS ENUM('full', 'subtle', 'off');
  CREATE TYPE "public"."enum__theme_v_version_heading_font" AS ENUM('Geist', 'Inter', 'Manrope', 'DM Sans', 'Space Grotesk', 'Plus Jakarta Sans', 'Sora', 'Outfit', 'Instrument Serif', 'Playfair Display', 'Fraunces', 'DM Serif Display');
  CREATE TYPE "public"."enum__theme_v_version_body_font" AS ENUM('Geist', 'Inter', 'Manrope', 'DM Sans', 'Space Grotesk', 'Plus Jakarta Sans', 'Sora', 'Outfit', 'Instrument Serif', 'Playfair Display', 'Fraunces', 'DM Serif Display');
  CREATE TYPE "public"."enum__theme_v_version_heading_weight" AS ENUM('300', '400', '500', '600', '700');
  CREATE TYPE "public"."enum__theme_v_version_button_shape" AS ENUM('pill', 'rounded', 'square');
  CREATE TYPE "public"."enum__theme_v_version_motion" AS ENUM('full', 'subtle', 'off');
  CREATE TABLE "theme" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"background" varchar DEFAULT '#000000',
  	"surface" varchar DEFAULT '#131313',
  	"text" varchar DEFAULT '#F5F5F4',
  	"muted_text" varchar DEFAULT '#A8A8A6',
  	"accent" varchar DEFAULT '#E8352B',
  	"accent2" varchar DEFAULT '#FF6A2B',
  	"light_background" varchar DEFAULT '#F2F2F1',
  	"light_surface" varchar DEFAULT '#FFFFFF',
  	"light_text" varchar DEFAULT '#0A0A0A',
  	"glow" boolean DEFAULT true,
  	"heading_font" "enum_theme_heading_font" DEFAULT 'Geist',
  	"body_font" "enum_theme_body_font" DEFAULT 'Geist',
  	"heading_weight" "enum_theme_heading_weight" DEFAULT '500',
  	"heading_tracking" numeric DEFAULT -4,
  	"base_size" numeric DEFAULT 16,
  	"button_background" varchar DEFAULT '#FFFFFF',
  	"button_text" varchar DEFAULT '#0A0A0A',
  	"button_dark_background" varchar DEFAULT '#0A0A0A',
  	"button_shape" "enum_theme_button_shape" DEFAULT 'pill',
  	"button_height" numeric DEFAULT 44,
  	"radius" numeric DEFAULT 100,
  	"spacing" numeric DEFAULT 100,
  	"container" numeric DEFAULT 1240,
  	"motion" "enum_theme_motion" DEFAULT 'full',
  	"updated_at" timestamp(3) with time zone,
  	"created_at" timestamp(3) with time zone
  );
  
  CREATE TABLE "_theme_v" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"version_background" varchar DEFAULT '#000000',
  	"version_surface" varchar DEFAULT '#131313',
  	"version_text" varchar DEFAULT '#F5F5F4',
  	"version_muted_text" varchar DEFAULT '#A8A8A6',
  	"version_accent" varchar DEFAULT '#E8352B',
  	"version_accent2" varchar DEFAULT '#FF6A2B',
  	"version_light_background" varchar DEFAULT '#F2F2F1',
  	"version_light_surface" varchar DEFAULT '#FFFFFF',
  	"version_light_text" varchar DEFAULT '#0A0A0A',
  	"version_glow" boolean DEFAULT true,
  	"version_heading_font" "enum__theme_v_version_heading_font" DEFAULT 'Geist',
  	"version_body_font" "enum__theme_v_version_body_font" DEFAULT 'Geist',
  	"version_heading_weight" "enum__theme_v_version_heading_weight" DEFAULT '500',
  	"version_heading_tracking" numeric DEFAULT -4,
  	"version_base_size" numeric DEFAULT 16,
  	"version_button_background" varchar DEFAULT '#FFFFFF',
  	"version_button_text" varchar DEFAULT '#0A0A0A',
  	"version_button_dark_background" varchar DEFAULT '#0A0A0A',
  	"version_button_shape" "enum__theme_v_version_button_shape" DEFAULT 'pill',
  	"version_button_height" numeric DEFAULT 44,
  	"version_radius" numeric DEFAULT 100,
  	"version_spacing" numeric DEFAULT 100,
  	"version_container" numeric DEFAULT 1240,
  	"version_motion" "enum__theme_v_version_motion" DEFAULT 'full',
  	"version_updated_at" timestamp(3) with time zone,
  	"version_created_at" timestamp(3) with time zone,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL
  );
  
  ALTER TABLE "pages_blocks_hero" ADD COLUMN "button_variant" "enum_pages_blocks_hero_button_variant" DEFAULT 'default';
  ALTER TABLE "pages_blocks_hero" ADD COLUMN "style_background" varchar;
  ALTER TABLE "pages_blocks_hero" ADD COLUMN "style_text" varchar;
  ALTER TABLE "pages_blocks_hero" ADD COLUMN "style_accent" varchar;
  ALTER TABLE "pages_blocks_hero" ADD COLUMN "style_padding_top" numeric;
  ALTER TABLE "pages_blocks_hero" ADD COLUMN "style_padding_bottom" numeric;
  ALTER TABLE "pages_blocks_hero" ADD COLUMN "style_min_height" numeric;
  ALTER TABLE "pages_blocks_hero" ADD COLUMN "style_width" "enum_pages_blocks_hero_style_width" DEFAULT 'default';
  ALTER TABLE "pages_blocks_hero" ADD COLUMN "style_align" "enum_pages_blocks_hero_style_align" DEFAULT 'default';
  ALTER TABLE "pages_blocks_hero" ADD COLUMN "style_visibility" "enum_pages_blocks_hero_style_visibility" DEFAULT 'all';
  ALTER TABLE "pages_blocks_work_showcase" ADD COLUMN "link_variant" "enum_pages_blocks_work_showcase_link_variant" DEFAULT 'default';
  ALTER TABLE "pages_blocks_work_showcase" ADD COLUMN "style_background" varchar;
  ALTER TABLE "pages_blocks_work_showcase" ADD COLUMN "style_text" varchar;
  ALTER TABLE "pages_blocks_work_showcase" ADD COLUMN "style_accent" varchar;
  ALTER TABLE "pages_blocks_work_showcase" ADD COLUMN "style_padding_top" numeric;
  ALTER TABLE "pages_blocks_work_showcase" ADD COLUMN "style_padding_bottom" numeric;
  ALTER TABLE "pages_blocks_work_showcase" ADD COLUMN "style_min_height" numeric;
  ALTER TABLE "pages_blocks_work_showcase" ADD COLUMN "style_width" "enum_pages_blocks_work_showcase_style_width" DEFAULT 'default';
  ALTER TABLE "pages_blocks_work_showcase" ADD COLUMN "style_align" "enum_pages_blocks_work_showcase_style_align" DEFAULT 'default';
  ALTER TABLE "pages_blocks_work_showcase" ADD COLUMN "style_visibility" "enum_pages_blocks_work_showcase_style_visibility" DEFAULT 'all';
  ALTER TABLE "pages_blocks_about_banner" ADD COLUMN "link_variant" "enum_pages_blocks_about_banner_link_variant" DEFAULT 'default';
  ALTER TABLE "pages_blocks_about_banner" ADD COLUMN "style_background" varchar;
  ALTER TABLE "pages_blocks_about_banner" ADD COLUMN "style_text" varchar;
  ALTER TABLE "pages_blocks_about_banner" ADD COLUMN "style_accent" varchar;
  ALTER TABLE "pages_blocks_about_banner" ADD COLUMN "style_padding_top" numeric;
  ALTER TABLE "pages_blocks_about_banner" ADD COLUMN "style_padding_bottom" numeric;
  ALTER TABLE "pages_blocks_about_banner" ADD COLUMN "style_min_height" numeric;
  ALTER TABLE "pages_blocks_about_banner" ADD COLUMN "style_width" "enum_pages_blocks_about_banner_style_width" DEFAULT 'default';
  ALTER TABLE "pages_blocks_about_banner" ADD COLUMN "style_align" "enum_pages_blocks_about_banner_style_align" DEFAULT 'default';
  ALTER TABLE "pages_blocks_about_banner" ADD COLUMN "style_visibility" "enum_pages_blocks_about_banner_style_visibility" DEFAULT 'all';
  ALTER TABLE "pages_blocks_audience" ADD COLUMN "style_background" varchar;
  ALTER TABLE "pages_blocks_audience" ADD COLUMN "style_text" varchar;
  ALTER TABLE "pages_blocks_audience" ADD COLUMN "style_accent" varchar;
  ALTER TABLE "pages_blocks_audience" ADD COLUMN "style_padding_top" numeric;
  ALTER TABLE "pages_blocks_audience" ADD COLUMN "style_padding_bottom" numeric;
  ALTER TABLE "pages_blocks_audience" ADD COLUMN "style_min_height" numeric;
  ALTER TABLE "pages_blocks_audience" ADD COLUMN "style_width" "enum_pages_blocks_audience_style_width" DEFAULT 'default';
  ALTER TABLE "pages_blocks_audience" ADD COLUMN "style_align" "enum_pages_blocks_audience_style_align" DEFAULT 'default';
  ALTER TABLE "pages_blocks_audience" ADD COLUMN "style_visibility" "enum_pages_blocks_audience_style_visibility" DEFAULT 'all';
  ALTER TABLE "pages_blocks_process" ADD COLUMN "style_background" varchar;
  ALTER TABLE "pages_blocks_process" ADD COLUMN "style_text" varchar;
  ALTER TABLE "pages_blocks_process" ADD COLUMN "style_accent" varchar;
  ALTER TABLE "pages_blocks_process" ADD COLUMN "style_padding_top" numeric;
  ALTER TABLE "pages_blocks_process" ADD COLUMN "style_padding_bottom" numeric;
  ALTER TABLE "pages_blocks_process" ADD COLUMN "style_min_height" numeric;
  ALTER TABLE "pages_blocks_process" ADD COLUMN "style_width" "enum_pages_blocks_process_style_width" DEFAULT 'default';
  ALTER TABLE "pages_blocks_process" ADD COLUMN "style_align" "enum_pages_blocks_process_style_align" DEFAULT 'default';
  ALTER TABLE "pages_blocks_process" ADD COLUMN "style_visibility" "enum_pages_blocks_process_style_visibility" DEFAULT 'all';
  ALTER TABLE "pages_blocks_services" ADD COLUMN "style_background" varchar;
  ALTER TABLE "pages_blocks_services" ADD COLUMN "style_text" varchar;
  ALTER TABLE "pages_blocks_services" ADD COLUMN "style_accent" varchar;
  ALTER TABLE "pages_blocks_services" ADD COLUMN "style_padding_top" numeric;
  ALTER TABLE "pages_blocks_services" ADD COLUMN "style_padding_bottom" numeric;
  ALTER TABLE "pages_blocks_services" ADD COLUMN "style_min_height" numeric;
  ALTER TABLE "pages_blocks_services" ADD COLUMN "style_width" "enum_pages_blocks_services_style_width" DEFAULT 'default';
  ALTER TABLE "pages_blocks_services" ADD COLUMN "style_align" "enum_pages_blocks_services_style_align" DEFAULT 'default';
  ALTER TABLE "pages_blocks_services" ADD COLUMN "style_visibility" "enum_pages_blocks_services_style_visibility" DEFAULT 'all';
  ALTER TABLE "pages_blocks_testimonials" ADD COLUMN "style_background" varchar;
  ALTER TABLE "pages_blocks_testimonials" ADD COLUMN "style_text" varchar;
  ALTER TABLE "pages_blocks_testimonials" ADD COLUMN "style_accent" varchar;
  ALTER TABLE "pages_blocks_testimonials" ADD COLUMN "style_padding_top" numeric;
  ALTER TABLE "pages_blocks_testimonials" ADD COLUMN "style_padding_bottom" numeric;
  ALTER TABLE "pages_blocks_testimonials" ADD COLUMN "style_min_height" numeric;
  ALTER TABLE "pages_blocks_testimonials" ADD COLUMN "style_width" "enum_pages_blocks_testimonials_style_width" DEFAULT 'default';
  ALTER TABLE "pages_blocks_testimonials" ADD COLUMN "style_align" "enum_pages_blocks_testimonials_style_align" DEFAULT 'default';
  ALTER TABLE "pages_blocks_testimonials" ADD COLUMN "style_visibility" "enum_pages_blocks_testimonials_style_visibility" DEFAULT 'all';
  ALTER TABLE "pages_blocks_contact" ADD COLUMN "style_background" varchar;
  ALTER TABLE "pages_blocks_contact" ADD COLUMN "style_text" varchar;
  ALTER TABLE "pages_blocks_contact" ADD COLUMN "style_accent" varchar;
  ALTER TABLE "pages_blocks_contact" ADD COLUMN "style_padding_top" numeric;
  ALTER TABLE "pages_blocks_contact" ADD COLUMN "style_padding_bottom" numeric;
  ALTER TABLE "pages_blocks_contact" ADD COLUMN "style_min_height" numeric;
  ALTER TABLE "pages_blocks_contact" ADD COLUMN "style_width" "enum_pages_blocks_contact_style_width" DEFAULT 'default';
  ALTER TABLE "pages_blocks_contact" ADD COLUMN "style_align" "enum_pages_blocks_contact_style_align" DEFAULT 'default';
  ALTER TABLE "pages_blocks_contact" ADD COLUMN "style_visibility" "enum_pages_blocks_contact_style_visibility" DEFAULT 'all';
  ALTER TABLE "pages_blocks_project_grid" ADD COLUMN "style_background" varchar;
  ALTER TABLE "pages_blocks_project_grid" ADD COLUMN "style_text" varchar;
  ALTER TABLE "pages_blocks_project_grid" ADD COLUMN "style_accent" varchar;
  ALTER TABLE "pages_blocks_project_grid" ADD COLUMN "style_padding_top" numeric;
  ALTER TABLE "pages_blocks_project_grid" ADD COLUMN "style_padding_bottom" numeric;
  ALTER TABLE "pages_blocks_project_grid" ADD COLUMN "style_min_height" numeric;
  ALTER TABLE "pages_blocks_project_grid" ADD COLUMN "style_width" "enum_pages_blocks_project_grid_style_width" DEFAULT 'default';
  ALTER TABLE "pages_blocks_project_grid" ADD COLUMN "style_align" "enum_pages_blocks_project_grid_style_align" DEFAULT 'default';
  ALTER TABLE "pages_blocks_project_grid" ADD COLUMN "style_visibility" "enum_pages_blocks_project_grid_style_visibility" DEFAULT 'all';
  ALTER TABLE "pages_blocks_profile" ADD COLUMN "button_variant" "enum_pages_blocks_profile_button_variant" DEFAULT 'default';
  ALTER TABLE "pages_blocks_profile" ADD COLUMN "style_background" varchar;
  ALTER TABLE "pages_blocks_profile" ADD COLUMN "style_text" varchar;
  ALTER TABLE "pages_blocks_profile" ADD COLUMN "style_accent" varchar;
  ALTER TABLE "pages_blocks_profile" ADD COLUMN "style_padding_top" numeric;
  ALTER TABLE "pages_blocks_profile" ADD COLUMN "style_padding_bottom" numeric;
  ALTER TABLE "pages_blocks_profile" ADD COLUMN "style_min_height" numeric;
  ALTER TABLE "pages_blocks_profile" ADD COLUMN "style_width" "enum_pages_blocks_profile_style_width" DEFAULT 'default';
  ALTER TABLE "pages_blocks_profile" ADD COLUMN "style_align" "enum_pages_blocks_profile_style_align" DEFAULT 'default';
  ALTER TABLE "pages_blocks_profile" ADD COLUMN "style_visibility" "enum_pages_blocks_profile_style_visibility" DEFAULT 'all';
  ALTER TABLE "pages_blocks_rich_text" ADD COLUMN "style_background" varchar;
  ALTER TABLE "pages_blocks_rich_text" ADD COLUMN "style_text" varchar;
  ALTER TABLE "pages_blocks_rich_text" ADD COLUMN "style_accent" varchar;
  ALTER TABLE "pages_blocks_rich_text" ADD COLUMN "style_padding_top" numeric;
  ALTER TABLE "pages_blocks_rich_text" ADD COLUMN "style_padding_bottom" numeric;
  ALTER TABLE "pages_blocks_rich_text" ADD COLUMN "style_min_height" numeric;
  ALTER TABLE "pages_blocks_rich_text" ADD COLUMN "style_width" "enum_pages_blocks_rich_text_style_width" DEFAULT 'default';
  ALTER TABLE "pages_blocks_rich_text" ADD COLUMN "style_align" "enum_pages_blocks_rich_text_style_align" DEFAULT 'default';
  ALTER TABLE "pages_blocks_rich_text" ADD COLUMN "style_visibility" "enum_pages_blocks_rich_text_style_visibility" DEFAULT 'all';
  ALTER TABLE "pages_blocks_media_section" ADD COLUMN "style_background" varchar;
  ALTER TABLE "pages_blocks_media_section" ADD COLUMN "style_text" varchar;
  ALTER TABLE "pages_blocks_media_section" ADD COLUMN "style_accent" varchar;
  ALTER TABLE "pages_blocks_media_section" ADD COLUMN "style_padding_top" numeric;
  ALTER TABLE "pages_blocks_media_section" ADD COLUMN "style_padding_bottom" numeric;
  ALTER TABLE "pages_blocks_media_section" ADD COLUMN "style_min_height" numeric;
  ALTER TABLE "pages_blocks_media_section" ADD COLUMN "style_width" "enum_pages_blocks_media_section_style_width" DEFAULT 'default';
  ALTER TABLE "pages_blocks_media_section" ADD COLUMN "style_align" "enum_pages_blocks_media_section_style_align" DEFAULT 'default';
  ALTER TABLE "pages_blocks_media_section" ADD COLUMN "style_visibility" "enum_pages_blocks_media_section_style_visibility" DEFAULT 'all';
  ALTER TABLE "pages_blocks_cta_banner" ADD COLUMN "button_variant" "enum_pages_blocks_cta_banner_button_variant" DEFAULT 'default';
  ALTER TABLE "pages_blocks_cta_banner" ADD COLUMN "style_background" varchar;
  ALTER TABLE "pages_blocks_cta_banner" ADD COLUMN "style_text" varchar;
  ALTER TABLE "pages_blocks_cta_banner" ADD COLUMN "style_accent" varchar;
  ALTER TABLE "pages_blocks_cta_banner" ADD COLUMN "style_padding_top" numeric;
  ALTER TABLE "pages_blocks_cta_banner" ADD COLUMN "style_padding_bottom" numeric;
  ALTER TABLE "pages_blocks_cta_banner" ADD COLUMN "style_min_height" numeric;
  ALTER TABLE "pages_blocks_cta_banner" ADD COLUMN "style_width" "enum_pages_blocks_cta_banner_style_width" DEFAULT 'default';
  ALTER TABLE "pages_blocks_cta_banner" ADD COLUMN "style_align" "enum_pages_blocks_cta_banner_style_align" DEFAULT 'default';
  ALTER TABLE "pages_blocks_cta_banner" ADD COLUMN "style_visibility" "enum_pages_blocks_cta_banner_style_visibility" DEFAULT 'all';
  ALTER TABLE "pages_blocks_faq" ADD COLUMN "style_background" varchar;
  ALTER TABLE "pages_blocks_faq" ADD COLUMN "style_text" varchar;
  ALTER TABLE "pages_blocks_faq" ADD COLUMN "style_accent" varchar;
  ALTER TABLE "pages_blocks_faq" ADD COLUMN "style_padding_top" numeric;
  ALTER TABLE "pages_blocks_faq" ADD COLUMN "style_padding_bottom" numeric;
  ALTER TABLE "pages_blocks_faq" ADD COLUMN "style_min_height" numeric;
  ALTER TABLE "pages_blocks_faq" ADD COLUMN "style_width" "enum_pages_blocks_faq_style_width" DEFAULT 'default';
  ALTER TABLE "pages_blocks_faq" ADD COLUMN "style_align" "enum_pages_blocks_faq_style_align" DEFAULT 'default';
  ALTER TABLE "pages_blocks_faq" ADD COLUMN "style_visibility" "enum_pages_blocks_faq_style_visibility" DEFAULT 'all';
  ALTER TABLE "_pages_v_blocks_hero" ADD COLUMN "button_variant" "enum__pages_v_blocks_hero_button_variant" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_hero" ADD COLUMN "style_background" varchar;
  ALTER TABLE "_pages_v_blocks_hero" ADD COLUMN "style_text" varchar;
  ALTER TABLE "_pages_v_blocks_hero" ADD COLUMN "style_accent" varchar;
  ALTER TABLE "_pages_v_blocks_hero" ADD COLUMN "style_padding_top" numeric;
  ALTER TABLE "_pages_v_blocks_hero" ADD COLUMN "style_padding_bottom" numeric;
  ALTER TABLE "_pages_v_blocks_hero" ADD COLUMN "style_min_height" numeric;
  ALTER TABLE "_pages_v_blocks_hero" ADD COLUMN "style_width" "enum__pages_v_blocks_hero_style_width" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_hero" ADD COLUMN "style_align" "enum__pages_v_blocks_hero_style_align" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_hero" ADD COLUMN "style_visibility" "enum__pages_v_blocks_hero_style_visibility" DEFAULT 'all';
  ALTER TABLE "_pages_v_blocks_work_showcase" ADD COLUMN "link_variant" "enum__pages_v_blocks_work_showcase_link_variant" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_work_showcase" ADD COLUMN "style_background" varchar;
  ALTER TABLE "_pages_v_blocks_work_showcase" ADD COLUMN "style_text" varchar;
  ALTER TABLE "_pages_v_blocks_work_showcase" ADD COLUMN "style_accent" varchar;
  ALTER TABLE "_pages_v_blocks_work_showcase" ADD COLUMN "style_padding_top" numeric;
  ALTER TABLE "_pages_v_blocks_work_showcase" ADD COLUMN "style_padding_bottom" numeric;
  ALTER TABLE "_pages_v_blocks_work_showcase" ADD COLUMN "style_min_height" numeric;
  ALTER TABLE "_pages_v_blocks_work_showcase" ADD COLUMN "style_width" "enum__pages_v_blocks_work_showcase_style_width" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_work_showcase" ADD COLUMN "style_align" "enum__pages_v_blocks_work_showcase_style_align" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_work_showcase" ADD COLUMN "style_visibility" "enum__pages_v_blocks_work_showcase_style_visibility" DEFAULT 'all';
  ALTER TABLE "_pages_v_blocks_about_banner" ADD COLUMN "link_variant" "enum__pages_v_blocks_about_banner_link_variant" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_about_banner" ADD COLUMN "style_background" varchar;
  ALTER TABLE "_pages_v_blocks_about_banner" ADD COLUMN "style_text" varchar;
  ALTER TABLE "_pages_v_blocks_about_banner" ADD COLUMN "style_accent" varchar;
  ALTER TABLE "_pages_v_blocks_about_banner" ADD COLUMN "style_padding_top" numeric;
  ALTER TABLE "_pages_v_blocks_about_banner" ADD COLUMN "style_padding_bottom" numeric;
  ALTER TABLE "_pages_v_blocks_about_banner" ADD COLUMN "style_min_height" numeric;
  ALTER TABLE "_pages_v_blocks_about_banner" ADD COLUMN "style_width" "enum__pages_v_blocks_about_banner_style_width" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_about_banner" ADD COLUMN "style_align" "enum__pages_v_blocks_about_banner_style_align" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_about_banner" ADD COLUMN "style_visibility" "enum__pages_v_blocks_about_banner_style_visibility" DEFAULT 'all';
  ALTER TABLE "_pages_v_blocks_audience" ADD COLUMN "style_background" varchar;
  ALTER TABLE "_pages_v_blocks_audience" ADD COLUMN "style_text" varchar;
  ALTER TABLE "_pages_v_blocks_audience" ADD COLUMN "style_accent" varchar;
  ALTER TABLE "_pages_v_blocks_audience" ADD COLUMN "style_padding_top" numeric;
  ALTER TABLE "_pages_v_blocks_audience" ADD COLUMN "style_padding_bottom" numeric;
  ALTER TABLE "_pages_v_blocks_audience" ADD COLUMN "style_min_height" numeric;
  ALTER TABLE "_pages_v_blocks_audience" ADD COLUMN "style_width" "enum__pages_v_blocks_audience_style_width" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_audience" ADD COLUMN "style_align" "enum__pages_v_blocks_audience_style_align" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_audience" ADD COLUMN "style_visibility" "enum__pages_v_blocks_audience_style_visibility" DEFAULT 'all';
  ALTER TABLE "_pages_v_blocks_process" ADD COLUMN "style_background" varchar;
  ALTER TABLE "_pages_v_blocks_process" ADD COLUMN "style_text" varchar;
  ALTER TABLE "_pages_v_blocks_process" ADD COLUMN "style_accent" varchar;
  ALTER TABLE "_pages_v_blocks_process" ADD COLUMN "style_padding_top" numeric;
  ALTER TABLE "_pages_v_blocks_process" ADD COLUMN "style_padding_bottom" numeric;
  ALTER TABLE "_pages_v_blocks_process" ADD COLUMN "style_min_height" numeric;
  ALTER TABLE "_pages_v_blocks_process" ADD COLUMN "style_width" "enum__pages_v_blocks_process_style_width" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_process" ADD COLUMN "style_align" "enum__pages_v_blocks_process_style_align" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_process" ADD COLUMN "style_visibility" "enum__pages_v_blocks_process_style_visibility" DEFAULT 'all';
  ALTER TABLE "_pages_v_blocks_services" ADD COLUMN "style_background" varchar;
  ALTER TABLE "_pages_v_blocks_services" ADD COLUMN "style_text" varchar;
  ALTER TABLE "_pages_v_blocks_services" ADD COLUMN "style_accent" varchar;
  ALTER TABLE "_pages_v_blocks_services" ADD COLUMN "style_padding_top" numeric;
  ALTER TABLE "_pages_v_blocks_services" ADD COLUMN "style_padding_bottom" numeric;
  ALTER TABLE "_pages_v_blocks_services" ADD COLUMN "style_min_height" numeric;
  ALTER TABLE "_pages_v_blocks_services" ADD COLUMN "style_width" "enum__pages_v_blocks_services_style_width" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_services" ADD COLUMN "style_align" "enum__pages_v_blocks_services_style_align" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_services" ADD COLUMN "style_visibility" "enum__pages_v_blocks_services_style_visibility" DEFAULT 'all';
  ALTER TABLE "_pages_v_blocks_testimonials" ADD COLUMN "style_background" varchar;
  ALTER TABLE "_pages_v_blocks_testimonials" ADD COLUMN "style_text" varchar;
  ALTER TABLE "_pages_v_blocks_testimonials" ADD COLUMN "style_accent" varchar;
  ALTER TABLE "_pages_v_blocks_testimonials" ADD COLUMN "style_padding_top" numeric;
  ALTER TABLE "_pages_v_blocks_testimonials" ADD COLUMN "style_padding_bottom" numeric;
  ALTER TABLE "_pages_v_blocks_testimonials" ADD COLUMN "style_min_height" numeric;
  ALTER TABLE "_pages_v_blocks_testimonials" ADD COLUMN "style_width" "enum__pages_v_blocks_testimonials_style_width" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_testimonials" ADD COLUMN "style_align" "enum__pages_v_blocks_testimonials_style_align" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_testimonials" ADD COLUMN "style_visibility" "enum__pages_v_blocks_testimonials_style_visibility" DEFAULT 'all';
  ALTER TABLE "_pages_v_blocks_contact" ADD COLUMN "style_background" varchar;
  ALTER TABLE "_pages_v_blocks_contact" ADD COLUMN "style_text" varchar;
  ALTER TABLE "_pages_v_blocks_contact" ADD COLUMN "style_accent" varchar;
  ALTER TABLE "_pages_v_blocks_contact" ADD COLUMN "style_padding_top" numeric;
  ALTER TABLE "_pages_v_blocks_contact" ADD COLUMN "style_padding_bottom" numeric;
  ALTER TABLE "_pages_v_blocks_contact" ADD COLUMN "style_min_height" numeric;
  ALTER TABLE "_pages_v_blocks_contact" ADD COLUMN "style_width" "enum__pages_v_blocks_contact_style_width" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_contact" ADD COLUMN "style_align" "enum__pages_v_blocks_contact_style_align" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_contact" ADD COLUMN "style_visibility" "enum__pages_v_blocks_contact_style_visibility" DEFAULT 'all';
  ALTER TABLE "_pages_v_blocks_project_grid" ADD COLUMN "style_background" varchar;
  ALTER TABLE "_pages_v_blocks_project_grid" ADD COLUMN "style_text" varchar;
  ALTER TABLE "_pages_v_blocks_project_grid" ADD COLUMN "style_accent" varchar;
  ALTER TABLE "_pages_v_blocks_project_grid" ADD COLUMN "style_padding_top" numeric;
  ALTER TABLE "_pages_v_blocks_project_grid" ADD COLUMN "style_padding_bottom" numeric;
  ALTER TABLE "_pages_v_blocks_project_grid" ADD COLUMN "style_min_height" numeric;
  ALTER TABLE "_pages_v_blocks_project_grid" ADD COLUMN "style_width" "enum__pages_v_blocks_project_grid_style_width" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_project_grid" ADD COLUMN "style_align" "enum__pages_v_blocks_project_grid_style_align" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_project_grid" ADD COLUMN "style_visibility" "enum__pages_v_blocks_project_grid_style_visibility" DEFAULT 'all';
  ALTER TABLE "_pages_v_blocks_profile" ADD COLUMN "button_variant" "enum__pages_v_blocks_profile_button_variant" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_profile" ADD COLUMN "style_background" varchar;
  ALTER TABLE "_pages_v_blocks_profile" ADD COLUMN "style_text" varchar;
  ALTER TABLE "_pages_v_blocks_profile" ADD COLUMN "style_accent" varchar;
  ALTER TABLE "_pages_v_blocks_profile" ADD COLUMN "style_padding_top" numeric;
  ALTER TABLE "_pages_v_blocks_profile" ADD COLUMN "style_padding_bottom" numeric;
  ALTER TABLE "_pages_v_blocks_profile" ADD COLUMN "style_min_height" numeric;
  ALTER TABLE "_pages_v_blocks_profile" ADD COLUMN "style_width" "enum__pages_v_blocks_profile_style_width" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_profile" ADD COLUMN "style_align" "enum__pages_v_blocks_profile_style_align" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_profile" ADD COLUMN "style_visibility" "enum__pages_v_blocks_profile_style_visibility" DEFAULT 'all';
  ALTER TABLE "_pages_v_blocks_rich_text" ADD COLUMN "style_background" varchar;
  ALTER TABLE "_pages_v_blocks_rich_text" ADD COLUMN "style_text" varchar;
  ALTER TABLE "_pages_v_blocks_rich_text" ADD COLUMN "style_accent" varchar;
  ALTER TABLE "_pages_v_blocks_rich_text" ADD COLUMN "style_padding_top" numeric;
  ALTER TABLE "_pages_v_blocks_rich_text" ADD COLUMN "style_padding_bottom" numeric;
  ALTER TABLE "_pages_v_blocks_rich_text" ADD COLUMN "style_min_height" numeric;
  ALTER TABLE "_pages_v_blocks_rich_text" ADD COLUMN "style_width" "enum__pages_v_blocks_rich_text_style_width" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_rich_text" ADD COLUMN "style_align" "enum__pages_v_blocks_rich_text_style_align" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_rich_text" ADD COLUMN "style_visibility" "enum__pages_v_blocks_rich_text_style_visibility" DEFAULT 'all';
  ALTER TABLE "_pages_v_blocks_media_section" ADD COLUMN "style_background" varchar;
  ALTER TABLE "_pages_v_blocks_media_section" ADD COLUMN "style_text" varchar;
  ALTER TABLE "_pages_v_blocks_media_section" ADD COLUMN "style_accent" varchar;
  ALTER TABLE "_pages_v_blocks_media_section" ADD COLUMN "style_padding_top" numeric;
  ALTER TABLE "_pages_v_blocks_media_section" ADD COLUMN "style_padding_bottom" numeric;
  ALTER TABLE "_pages_v_blocks_media_section" ADD COLUMN "style_min_height" numeric;
  ALTER TABLE "_pages_v_blocks_media_section" ADD COLUMN "style_width" "enum__pages_v_blocks_media_section_style_width" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_media_section" ADD COLUMN "style_align" "enum__pages_v_blocks_media_section_style_align" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_media_section" ADD COLUMN "style_visibility" "enum__pages_v_blocks_media_section_style_visibility" DEFAULT 'all';
  ALTER TABLE "_pages_v_blocks_cta_banner" ADD COLUMN "button_variant" "enum__pages_v_blocks_cta_banner_button_variant" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_cta_banner" ADD COLUMN "style_background" varchar;
  ALTER TABLE "_pages_v_blocks_cta_banner" ADD COLUMN "style_text" varchar;
  ALTER TABLE "_pages_v_blocks_cta_banner" ADD COLUMN "style_accent" varchar;
  ALTER TABLE "_pages_v_blocks_cta_banner" ADD COLUMN "style_padding_top" numeric;
  ALTER TABLE "_pages_v_blocks_cta_banner" ADD COLUMN "style_padding_bottom" numeric;
  ALTER TABLE "_pages_v_blocks_cta_banner" ADD COLUMN "style_min_height" numeric;
  ALTER TABLE "_pages_v_blocks_cta_banner" ADD COLUMN "style_width" "enum__pages_v_blocks_cta_banner_style_width" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_cta_banner" ADD COLUMN "style_align" "enum__pages_v_blocks_cta_banner_style_align" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_cta_banner" ADD COLUMN "style_visibility" "enum__pages_v_blocks_cta_banner_style_visibility" DEFAULT 'all';
  ALTER TABLE "_pages_v_blocks_faq" ADD COLUMN "style_background" varchar;
  ALTER TABLE "_pages_v_blocks_faq" ADD COLUMN "style_text" varchar;
  ALTER TABLE "_pages_v_blocks_faq" ADD COLUMN "style_accent" varchar;
  ALTER TABLE "_pages_v_blocks_faq" ADD COLUMN "style_padding_top" numeric;
  ALTER TABLE "_pages_v_blocks_faq" ADD COLUMN "style_padding_bottom" numeric;
  ALTER TABLE "_pages_v_blocks_faq" ADD COLUMN "style_min_height" numeric;
  ALTER TABLE "_pages_v_blocks_faq" ADD COLUMN "style_width" "enum__pages_v_blocks_faq_style_width" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_faq" ADD COLUMN "style_align" "enum__pages_v_blocks_faq_style_align" DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_faq" ADD COLUMN "style_visibility" "enum__pages_v_blocks_faq_style_visibility" DEFAULT 'all';
  CREATE INDEX "_theme_v_created_at_idx" ON "_theme_v" USING btree ("created_at");
  CREATE INDEX "_theme_v_updated_at_idx" ON "_theme_v" USING btree ("updated_at");`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   DROP TABLE "theme" CASCADE;
  DROP TABLE "_theme_v" CASCADE;
  ALTER TABLE "pages_blocks_hero" DROP COLUMN "button_variant";
  ALTER TABLE "pages_blocks_hero" DROP COLUMN "style_background";
  ALTER TABLE "pages_blocks_hero" DROP COLUMN "style_text";
  ALTER TABLE "pages_blocks_hero" DROP COLUMN "style_accent";
  ALTER TABLE "pages_blocks_hero" DROP COLUMN "style_padding_top";
  ALTER TABLE "pages_blocks_hero" DROP COLUMN "style_padding_bottom";
  ALTER TABLE "pages_blocks_hero" DROP COLUMN "style_min_height";
  ALTER TABLE "pages_blocks_hero" DROP COLUMN "style_width";
  ALTER TABLE "pages_blocks_hero" DROP COLUMN "style_align";
  ALTER TABLE "pages_blocks_hero" DROP COLUMN "style_visibility";
  ALTER TABLE "pages_blocks_work_showcase" DROP COLUMN "link_variant";
  ALTER TABLE "pages_blocks_work_showcase" DROP COLUMN "style_background";
  ALTER TABLE "pages_blocks_work_showcase" DROP COLUMN "style_text";
  ALTER TABLE "pages_blocks_work_showcase" DROP COLUMN "style_accent";
  ALTER TABLE "pages_blocks_work_showcase" DROP COLUMN "style_padding_top";
  ALTER TABLE "pages_blocks_work_showcase" DROP COLUMN "style_padding_bottom";
  ALTER TABLE "pages_blocks_work_showcase" DROP COLUMN "style_min_height";
  ALTER TABLE "pages_blocks_work_showcase" DROP COLUMN "style_width";
  ALTER TABLE "pages_blocks_work_showcase" DROP COLUMN "style_align";
  ALTER TABLE "pages_blocks_work_showcase" DROP COLUMN "style_visibility";
  ALTER TABLE "pages_blocks_about_banner" DROP COLUMN "link_variant";
  ALTER TABLE "pages_blocks_about_banner" DROP COLUMN "style_background";
  ALTER TABLE "pages_blocks_about_banner" DROP COLUMN "style_text";
  ALTER TABLE "pages_blocks_about_banner" DROP COLUMN "style_accent";
  ALTER TABLE "pages_blocks_about_banner" DROP COLUMN "style_padding_top";
  ALTER TABLE "pages_blocks_about_banner" DROP COLUMN "style_padding_bottom";
  ALTER TABLE "pages_blocks_about_banner" DROP COLUMN "style_min_height";
  ALTER TABLE "pages_blocks_about_banner" DROP COLUMN "style_width";
  ALTER TABLE "pages_blocks_about_banner" DROP COLUMN "style_align";
  ALTER TABLE "pages_blocks_about_banner" DROP COLUMN "style_visibility";
  ALTER TABLE "pages_blocks_audience" DROP COLUMN "style_background";
  ALTER TABLE "pages_blocks_audience" DROP COLUMN "style_text";
  ALTER TABLE "pages_blocks_audience" DROP COLUMN "style_accent";
  ALTER TABLE "pages_blocks_audience" DROP COLUMN "style_padding_top";
  ALTER TABLE "pages_blocks_audience" DROP COLUMN "style_padding_bottom";
  ALTER TABLE "pages_blocks_audience" DROP COLUMN "style_min_height";
  ALTER TABLE "pages_blocks_audience" DROP COLUMN "style_width";
  ALTER TABLE "pages_blocks_audience" DROP COLUMN "style_align";
  ALTER TABLE "pages_blocks_audience" DROP COLUMN "style_visibility";
  ALTER TABLE "pages_blocks_process" DROP COLUMN "style_background";
  ALTER TABLE "pages_blocks_process" DROP COLUMN "style_text";
  ALTER TABLE "pages_blocks_process" DROP COLUMN "style_accent";
  ALTER TABLE "pages_blocks_process" DROP COLUMN "style_padding_top";
  ALTER TABLE "pages_blocks_process" DROP COLUMN "style_padding_bottom";
  ALTER TABLE "pages_blocks_process" DROP COLUMN "style_min_height";
  ALTER TABLE "pages_blocks_process" DROP COLUMN "style_width";
  ALTER TABLE "pages_blocks_process" DROP COLUMN "style_align";
  ALTER TABLE "pages_blocks_process" DROP COLUMN "style_visibility";
  ALTER TABLE "pages_blocks_services" DROP COLUMN "style_background";
  ALTER TABLE "pages_blocks_services" DROP COLUMN "style_text";
  ALTER TABLE "pages_blocks_services" DROP COLUMN "style_accent";
  ALTER TABLE "pages_blocks_services" DROP COLUMN "style_padding_top";
  ALTER TABLE "pages_blocks_services" DROP COLUMN "style_padding_bottom";
  ALTER TABLE "pages_blocks_services" DROP COLUMN "style_min_height";
  ALTER TABLE "pages_blocks_services" DROP COLUMN "style_width";
  ALTER TABLE "pages_blocks_services" DROP COLUMN "style_align";
  ALTER TABLE "pages_blocks_services" DROP COLUMN "style_visibility";
  ALTER TABLE "pages_blocks_testimonials" DROP COLUMN "style_background";
  ALTER TABLE "pages_blocks_testimonials" DROP COLUMN "style_text";
  ALTER TABLE "pages_blocks_testimonials" DROP COLUMN "style_accent";
  ALTER TABLE "pages_blocks_testimonials" DROP COLUMN "style_padding_top";
  ALTER TABLE "pages_blocks_testimonials" DROP COLUMN "style_padding_bottom";
  ALTER TABLE "pages_blocks_testimonials" DROP COLUMN "style_min_height";
  ALTER TABLE "pages_blocks_testimonials" DROP COLUMN "style_width";
  ALTER TABLE "pages_blocks_testimonials" DROP COLUMN "style_align";
  ALTER TABLE "pages_blocks_testimonials" DROP COLUMN "style_visibility";
  ALTER TABLE "pages_blocks_contact" DROP COLUMN "style_background";
  ALTER TABLE "pages_blocks_contact" DROP COLUMN "style_text";
  ALTER TABLE "pages_blocks_contact" DROP COLUMN "style_accent";
  ALTER TABLE "pages_blocks_contact" DROP COLUMN "style_padding_top";
  ALTER TABLE "pages_blocks_contact" DROP COLUMN "style_padding_bottom";
  ALTER TABLE "pages_blocks_contact" DROP COLUMN "style_min_height";
  ALTER TABLE "pages_blocks_contact" DROP COLUMN "style_width";
  ALTER TABLE "pages_blocks_contact" DROP COLUMN "style_align";
  ALTER TABLE "pages_blocks_contact" DROP COLUMN "style_visibility";
  ALTER TABLE "pages_blocks_project_grid" DROP COLUMN "style_background";
  ALTER TABLE "pages_blocks_project_grid" DROP COLUMN "style_text";
  ALTER TABLE "pages_blocks_project_grid" DROP COLUMN "style_accent";
  ALTER TABLE "pages_blocks_project_grid" DROP COLUMN "style_padding_top";
  ALTER TABLE "pages_blocks_project_grid" DROP COLUMN "style_padding_bottom";
  ALTER TABLE "pages_blocks_project_grid" DROP COLUMN "style_min_height";
  ALTER TABLE "pages_blocks_project_grid" DROP COLUMN "style_width";
  ALTER TABLE "pages_blocks_project_grid" DROP COLUMN "style_align";
  ALTER TABLE "pages_blocks_project_grid" DROP COLUMN "style_visibility";
  ALTER TABLE "pages_blocks_profile" DROP COLUMN "button_variant";
  ALTER TABLE "pages_blocks_profile" DROP COLUMN "style_background";
  ALTER TABLE "pages_blocks_profile" DROP COLUMN "style_text";
  ALTER TABLE "pages_blocks_profile" DROP COLUMN "style_accent";
  ALTER TABLE "pages_blocks_profile" DROP COLUMN "style_padding_top";
  ALTER TABLE "pages_blocks_profile" DROP COLUMN "style_padding_bottom";
  ALTER TABLE "pages_blocks_profile" DROP COLUMN "style_min_height";
  ALTER TABLE "pages_blocks_profile" DROP COLUMN "style_width";
  ALTER TABLE "pages_blocks_profile" DROP COLUMN "style_align";
  ALTER TABLE "pages_blocks_profile" DROP COLUMN "style_visibility";
  ALTER TABLE "pages_blocks_rich_text" DROP COLUMN "style_background";
  ALTER TABLE "pages_blocks_rich_text" DROP COLUMN "style_text";
  ALTER TABLE "pages_blocks_rich_text" DROP COLUMN "style_accent";
  ALTER TABLE "pages_blocks_rich_text" DROP COLUMN "style_padding_top";
  ALTER TABLE "pages_blocks_rich_text" DROP COLUMN "style_padding_bottom";
  ALTER TABLE "pages_blocks_rich_text" DROP COLUMN "style_min_height";
  ALTER TABLE "pages_blocks_rich_text" DROP COLUMN "style_width";
  ALTER TABLE "pages_blocks_rich_text" DROP COLUMN "style_align";
  ALTER TABLE "pages_blocks_rich_text" DROP COLUMN "style_visibility";
  ALTER TABLE "pages_blocks_media_section" DROP COLUMN "style_background";
  ALTER TABLE "pages_blocks_media_section" DROP COLUMN "style_text";
  ALTER TABLE "pages_blocks_media_section" DROP COLUMN "style_accent";
  ALTER TABLE "pages_blocks_media_section" DROP COLUMN "style_padding_top";
  ALTER TABLE "pages_blocks_media_section" DROP COLUMN "style_padding_bottom";
  ALTER TABLE "pages_blocks_media_section" DROP COLUMN "style_min_height";
  ALTER TABLE "pages_blocks_media_section" DROP COLUMN "style_width";
  ALTER TABLE "pages_blocks_media_section" DROP COLUMN "style_align";
  ALTER TABLE "pages_blocks_media_section" DROP COLUMN "style_visibility";
  ALTER TABLE "pages_blocks_cta_banner" DROP COLUMN "button_variant";
  ALTER TABLE "pages_blocks_cta_banner" DROP COLUMN "style_background";
  ALTER TABLE "pages_blocks_cta_banner" DROP COLUMN "style_text";
  ALTER TABLE "pages_blocks_cta_banner" DROP COLUMN "style_accent";
  ALTER TABLE "pages_blocks_cta_banner" DROP COLUMN "style_padding_top";
  ALTER TABLE "pages_blocks_cta_banner" DROP COLUMN "style_padding_bottom";
  ALTER TABLE "pages_blocks_cta_banner" DROP COLUMN "style_min_height";
  ALTER TABLE "pages_blocks_cta_banner" DROP COLUMN "style_width";
  ALTER TABLE "pages_blocks_cta_banner" DROP COLUMN "style_align";
  ALTER TABLE "pages_blocks_cta_banner" DROP COLUMN "style_visibility";
  ALTER TABLE "pages_blocks_faq" DROP COLUMN "style_background";
  ALTER TABLE "pages_blocks_faq" DROP COLUMN "style_text";
  ALTER TABLE "pages_blocks_faq" DROP COLUMN "style_accent";
  ALTER TABLE "pages_blocks_faq" DROP COLUMN "style_padding_top";
  ALTER TABLE "pages_blocks_faq" DROP COLUMN "style_padding_bottom";
  ALTER TABLE "pages_blocks_faq" DROP COLUMN "style_min_height";
  ALTER TABLE "pages_blocks_faq" DROP COLUMN "style_width";
  ALTER TABLE "pages_blocks_faq" DROP COLUMN "style_align";
  ALTER TABLE "pages_blocks_faq" DROP COLUMN "style_visibility";
  ALTER TABLE "_pages_v_blocks_hero" DROP COLUMN "button_variant";
  ALTER TABLE "_pages_v_blocks_hero" DROP COLUMN "style_background";
  ALTER TABLE "_pages_v_blocks_hero" DROP COLUMN "style_text";
  ALTER TABLE "_pages_v_blocks_hero" DROP COLUMN "style_accent";
  ALTER TABLE "_pages_v_blocks_hero" DROP COLUMN "style_padding_top";
  ALTER TABLE "_pages_v_blocks_hero" DROP COLUMN "style_padding_bottom";
  ALTER TABLE "_pages_v_blocks_hero" DROP COLUMN "style_min_height";
  ALTER TABLE "_pages_v_blocks_hero" DROP COLUMN "style_width";
  ALTER TABLE "_pages_v_blocks_hero" DROP COLUMN "style_align";
  ALTER TABLE "_pages_v_blocks_hero" DROP COLUMN "style_visibility";
  ALTER TABLE "_pages_v_blocks_work_showcase" DROP COLUMN "link_variant";
  ALTER TABLE "_pages_v_blocks_work_showcase" DROP COLUMN "style_background";
  ALTER TABLE "_pages_v_blocks_work_showcase" DROP COLUMN "style_text";
  ALTER TABLE "_pages_v_blocks_work_showcase" DROP COLUMN "style_accent";
  ALTER TABLE "_pages_v_blocks_work_showcase" DROP COLUMN "style_padding_top";
  ALTER TABLE "_pages_v_blocks_work_showcase" DROP COLUMN "style_padding_bottom";
  ALTER TABLE "_pages_v_blocks_work_showcase" DROP COLUMN "style_min_height";
  ALTER TABLE "_pages_v_blocks_work_showcase" DROP COLUMN "style_width";
  ALTER TABLE "_pages_v_blocks_work_showcase" DROP COLUMN "style_align";
  ALTER TABLE "_pages_v_blocks_work_showcase" DROP COLUMN "style_visibility";
  ALTER TABLE "_pages_v_blocks_about_banner" DROP COLUMN "link_variant";
  ALTER TABLE "_pages_v_blocks_about_banner" DROP COLUMN "style_background";
  ALTER TABLE "_pages_v_blocks_about_banner" DROP COLUMN "style_text";
  ALTER TABLE "_pages_v_blocks_about_banner" DROP COLUMN "style_accent";
  ALTER TABLE "_pages_v_blocks_about_banner" DROP COLUMN "style_padding_top";
  ALTER TABLE "_pages_v_blocks_about_banner" DROP COLUMN "style_padding_bottom";
  ALTER TABLE "_pages_v_blocks_about_banner" DROP COLUMN "style_min_height";
  ALTER TABLE "_pages_v_blocks_about_banner" DROP COLUMN "style_width";
  ALTER TABLE "_pages_v_blocks_about_banner" DROP COLUMN "style_align";
  ALTER TABLE "_pages_v_blocks_about_banner" DROP COLUMN "style_visibility";
  ALTER TABLE "_pages_v_blocks_audience" DROP COLUMN "style_background";
  ALTER TABLE "_pages_v_blocks_audience" DROP COLUMN "style_text";
  ALTER TABLE "_pages_v_blocks_audience" DROP COLUMN "style_accent";
  ALTER TABLE "_pages_v_blocks_audience" DROP COLUMN "style_padding_top";
  ALTER TABLE "_pages_v_blocks_audience" DROP COLUMN "style_padding_bottom";
  ALTER TABLE "_pages_v_blocks_audience" DROP COLUMN "style_min_height";
  ALTER TABLE "_pages_v_blocks_audience" DROP COLUMN "style_width";
  ALTER TABLE "_pages_v_blocks_audience" DROP COLUMN "style_align";
  ALTER TABLE "_pages_v_blocks_audience" DROP COLUMN "style_visibility";
  ALTER TABLE "_pages_v_blocks_process" DROP COLUMN "style_background";
  ALTER TABLE "_pages_v_blocks_process" DROP COLUMN "style_text";
  ALTER TABLE "_pages_v_blocks_process" DROP COLUMN "style_accent";
  ALTER TABLE "_pages_v_blocks_process" DROP COLUMN "style_padding_top";
  ALTER TABLE "_pages_v_blocks_process" DROP COLUMN "style_padding_bottom";
  ALTER TABLE "_pages_v_blocks_process" DROP COLUMN "style_min_height";
  ALTER TABLE "_pages_v_blocks_process" DROP COLUMN "style_width";
  ALTER TABLE "_pages_v_blocks_process" DROP COLUMN "style_align";
  ALTER TABLE "_pages_v_blocks_process" DROP COLUMN "style_visibility";
  ALTER TABLE "_pages_v_blocks_services" DROP COLUMN "style_background";
  ALTER TABLE "_pages_v_blocks_services" DROP COLUMN "style_text";
  ALTER TABLE "_pages_v_blocks_services" DROP COLUMN "style_accent";
  ALTER TABLE "_pages_v_blocks_services" DROP COLUMN "style_padding_top";
  ALTER TABLE "_pages_v_blocks_services" DROP COLUMN "style_padding_bottom";
  ALTER TABLE "_pages_v_blocks_services" DROP COLUMN "style_min_height";
  ALTER TABLE "_pages_v_blocks_services" DROP COLUMN "style_width";
  ALTER TABLE "_pages_v_blocks_services" DROP COLUMN "style_align";
  ALTER TABLE "_pages_v_blocks_services" DROP COLUMN "style_visibility";
  ALTER TABLE "_pages_v_blocks_testimonials" DROP COLUMN "style_background";
  ALTER TABLE "_pages_v_blocks_testimonials" DROP COLUMN "style_text";
  ALTER TABLE "_pages_v_blocks_testimonials" DROP COLUMN "style_accent";
  ALTER TABLE "_pages_v_blocks_testimonials" DROP COLUMN "style_padding_top";
  ALTER TABLE "_pages_v_blocks_testimonials" DROP COLUMN "style_padding_bottom";
  ALTER TABLE "_pages_v_blocks_testimonials" DROP COLUMN "style_min_height";
  ALTER TABLE "_pages_v_blocks_testimonials" DROP COLUMN "style_width";
  ALTER TABLE "_pages_v_blocks_testimonials" DROP COLUMN "style_align";
  ALTER TABLE "_pages_v_blocks_testimonials" DROP COLUMN "style_visibility";
  ALTER TABLE "_pages_v_blocks_contact" DROP COLUMN "style_background";
  ALTER TABLE "_pages_v_blocks_contact" DROP COLUMN "style_text";
  ALTER TABLE "_pages_v_blocks_contact" DROP COLUMN "style_accent";
  ALTER TABLE "_pages_v_blocks_contact" DROP COLUMN "style_padding_top";
  ALTER TABLE "_pages_v_blocks_contact" DROP COLUMN "style_padding_bottom";
  ALTER TABLE "_pages_v_blocks_contact" DROP COLUMN "style_min_height";
  ALTER TABLE "_pages_v_blocks_contact" DROP COLUMN "style_width";
  ALTER TABLE "_pages_v_blocks_contact" DROP COLUMN "style_align";
  ALTER TABLE "_pages_v_blocks_contact" DROP COLUMN "style_visibility";
  ALTER TABLE "_pages_v_blocks_project_grid" DROP COLUMN "style_background";
  ALTER TABLE "_pages_v_blocks_project_grid" DROP COLUMN "style_text";
  ALTER TABLE "_pages_v_blocks_project_grid" DROP COLUMN "style_accent";
  ALTER TABLE "_pages_v_blocks_project_grid" DROP COLUMN "style_padding_top";
  ALTER TABLE "_pages_v_blocks_project_grid" DROP COLUMN "style_padding_bottom";
  ALTER TABLE "_pages_v_blocks_project_grid" DROP COLUMN "style_min_height";
  ALTER TABLE "_pages_v_blocks_project_grid" DROP COLUMN "style_width";
  ALTER TABLE "_pages_v_blocks_project_grid" DROP COLUMN "style_align";
  ALTER TABLE "_pages_v_blocks_project_grid" DROP COLUMN "style_visibility";
  ALTER TABLE "_pages_v_blocks_profile" DROP COLUMN "button_variant";
  ALTER TABLE "_pages_v_blocks_profile" DROP COLUMN "style_background";
  ALTER TABLE "_pages_v_blocks_profile" DROP COLUMN "style_text";
  ALTER TABLE "_pages_v_blocks_profile" DROP COLUMN "style_accent";
  ALTER TABLE "_pages_v_blocks_profile" DROP COLUMN "style_padding_top";
  ALTER TABLE "_pages_v_blocks_profile" DROP COLUMN "style_padding_bottom";
  ALTER TABLE "_pages_v_blocks_profile" DROP COLUMN "style_min_height";
  ALTER TABLE "_pages_v_blocks_profile" DROP COLUMN "style_width";
  ALTER TABLE "_pages_v_blocks_profile" DROP COLUMN "style_align";
  ALTER TABLE "_pages_v_blocks_profile" DROP COLUMN "style_visibility";
  ALTER TABLE "_pages_v_blocks_rich_text" DROP COLUMN "style_background";
  ALTER TABLE "_pages_v_blocks_rich_text" DROP COLUMN "style_text";
  ALTER TABLE "_pages_v_blocks_rich_text" DROP COLUMN "style_accent";
  ALTER TABLE "_pages_v_blocks_rich_text" DROP COLUMN "style_padding_top";
  ALTER TABLE "_pages_v_blocks_rich_text" DROP COLUMN "style_padding_bottom";
  ALTER TABLE "_pages_v_blocks_rich_text" DROP COLUMN "style_min_height";
  ALTER TABLE "_pages_v_blocks_rich_text" DROP COLUMN "style_width";
  ALTER TABLE "_pages_v_blocks_rich_text" DROP COLUMN "style_align";
  ALTER TABLE "_pages_v_blocks_rich_text" DROP COLUMN "style_visibility";
  ALTER TABLE "_pages_v_blocks_media_section" DROP COLUMN "style_background";
  ALTER TABLE "_pages_v_blocks_media_section" DROP COLUMN "style_text";
  ALTER TABLE "_pages_v_blocks_media_section" DROP COLUMN "style_accent";
  ALTER TABLE "_pages_v_blocks_media_section" DROP COLUMN "style_padding_top";
  ALTER TABLE "_pages_v_blocks_media_section" DROP COLUMN "style_padding_bottom";
  ALTER TABLE "_pages_v_blocks_media_section" DROP COLUMN "style_min_height";
  ALTER TABLE "_pages_v_blocks_media_section" DROP COLUMN "style_width";
  ALTER TABLE "_pages_v_blocks_media_section" DROP COLUMN "style_align";
  ALTER TABLE "_pages_v_blocks_media_section" DROP COLUMN "style_visibility";
  ALTER TABLE "_pages_v_blocks_cta_banner" DROP COLUMN "button_variant";
  ALTER TABLE "_pages_v_blocks_cta_banner" DROP COLUMN "style_background";
  ALTER TABLE "_pages_v_blocks_cta_banner" DROP COLUMN "style_text";
  ALTER TABLE "_pages_v_blocks_cta_banner" DROP COLUMN "style_accent";
  ALTER TABLE "_pages_v_blocks_cta_banner" DROP COLUMN "style_padding_top";
  ALTER TABLE "_pages_v_blocks_cta_banner" DROP COLUMN "style_padding_bottom";
  ALTER TABLE "_pages_v_blocks_cta_banner" DROP COLUMN "style_min_height";
  ALTER TABLE "_pages_v_blocks_cta_banner" DROP COLUMN "style_width";
  ALTER TABLE "_pages_v_blocks_cta_banner" DROP COLUMN "style_align";
  ALTER TABLE "_pages_v_blocks_cta_banner" DROP COLUMN "style_visibility";
  ALTER TABLE "_pages_v_blocks_faq" DROP COLUMN "style_background";
  ALTER TABLE "_pages_v_blocks_faq" DROP COLUMN "style_text";
  ALTER TABLE "_pages_v_blocks_faq" DROP COLUMN "style_accent";
  ALTER TABLE "_pages_v_blocks_faq" DROP COLUMN "style_padding_top";
  ALTER TABLE "_pages_v_blocks_faq" DROP COLUMN "style_padding_bottom";
  ALTER TABLE "_pages_v_blocks_faq" DROP COLUMN "style_min_height";
  ALTER TABLE "_pages_v_blocks_faq" DROP COLUMN "style_width";
  ALTER TABLE "_pages_v_blocks_faq" DROP COLUMN "style_align";
  ALTER TABLE "_pages_v_blocks_faq" DROP COLUMN "style_visibility";
  DROP TYPE "public"."enum_pages_blocks_hero_button_variant";
  DROP TYPE "public"."enum_pages_blocks_hero_style_width";
  DROP TYPE "public"."enum_pages_blocks_hero_style_align";
  DROP TYPE "public"."enum_pages_blocks_hero_style_visibility";
  DROP TYPE "public"."enum_pages_blocks_work_showcase_link_variant";
  DROP TYPE "public"."enum_pages_blocks_work_showcase_style_width";
  DROP TYPE "public"."enum_pages_blocks_work_showcase_style_align";
  DROP TYPE "public"."enum_pages_blocks_work_showcase_style_visibility";
  DROP TYPE "public"."enum_pages_blocks_about_banner_link_variant";
  DROP TYPE "public"."enum_pages_blocks_about_banner_style_width";
  DROP TYPE "public"."enum_pages_blocks_about_banner_style_align";
  DROP TYPE "public"."enum_pages_blocks_about_banner_style_visibility";
  DROP TYPE "public"."enum_pages_blocks_audience_style_width";
  DROP TYPE "public"."enum_pages_blocks_audience_style_align";
  DROP TYPE "public"."enum_pages_blocks_audience_style_visibility";
  DROP TYPE "public"."enum_pages_blocks_process_style_width";
  DROP TYPE "public"."enum_pages_blocks_process_style_align";
  DROP TYPE "public"."enum_pages_blocks_process_style_visibility";
  DROP TYPE "public"."enum_pages_blocks_services_style_width";
  DROP TYPE "public"."enum_pages_blocks_services_style_align";
  DROP TYPE "public"."enum_pages_blocks_services_style_visibility";
  DROP TYPE "public"."enum_pages_blocks_testimonials_style_width";
  DROP TYPE "public"."enum_pages_blocks_testimonials_style_align";
  DROP TYPE "public"."enum_pages_blocks_testimonials_style_visibility";
  DROP TYPE "public"."enum_pages_blocks_contact_style_width";
  DROP TYPE "public"."enum_pages_blocks_contact_style_align";
  DROP TYPE "public"."enum_pages_blocks_contact_style_visibility";
  DROP TYPE "public"."enum_pages_blocks_project_grid_style_width";
  DROP TYPE "public"."enum_pages_blocks_project_grid_style_align";
  DROP TYPE "public"."enum_pages_blocks_project_grid_style_visibility";
  DROP TYPE "public"."enum_pages_blocks_profile_button_variant";
  DROP TYPE "public"."enum_pages_blocks_profile_style_width";
  DROP TYPE "public"."enum_pages_blocks_profile_style_align";
  DROP TYPE "public"."enum_pages_blocks_profile_style_visibility";
  DROP TYPE "public"."enum_pages_blocks_rich_text_style_width";
  DROP TYPE "public"."enum_pages_blocks_rich_text_style_align";
  DROP TYPE "public"."enum_pages_blocks_rich_text_style_visibility";
  DROP TYPE "public"."enum_pages_blocks_media_section_style_width";
  DROP TYPE "public"."enum_pages_blocks_media_section_style_align";
  DROP TYPE "public"."enum_pages_blocks_media_section_style_visibility";
  DROP TYPE "public"."enum_pages_blocks_cta_banner_button_variant";
  DROP TYPE "public"."enum_pages_blocks_cta_banner_style_width";
  DROP TYPE "public"."enum_pages_blocks_cta_banner_style_align";
  DROP TYPE "public"."enum_pages_blocks_cta_banner_style_visibility";
  DROP TYPE "public"."enum_pages_blocks_faq_style_width";
  DROP TYPE "public"."enum_pages_blocks_faq_style_align";
  DROP TYPE "public"."enum_pages_blocks_faq_style_visibility";
  DROP TYPE "public"."enum__pages_v_blocks_hero_button_variant";
  DROP TYPE "public"."enum__pages_v_blocks_hero_style_width";
  DROP TYPE "public"."enum__pages_v_blocks_hero_style_align";
  DROP TYPE "public"."enum__pages_v_blocks_hero_style_visibility";
  DROP TYPE "public"."enum__pages_v_blocks_work_showcase_link_variant";
  DROP TYPE "public"."enum__pages_v_blocks_work_showcase_style_width";
  DROP TYPE "public"."enum__pages_v_blocks_work_showcase_style_align";
  DROP TYPE "public"."enum__pages_v_blocks_work_showcase_style_visibility";
  DROP TYPE "public"."enum__pages_v_blocks_about_banner_link_variant";
  DROP TYPE "public"."enum__pages_v_blocks_about_banner_style_width";
  DROP TYPE "public"."enum__pages_v_blocks_about_banner_style_align";
  DROP TYPE "public"."enum__pages_v_blocks_about_banner_style_visibility";
  DROP TYPE "public"."enum__pages_v_blocks_audience_style_width";
  DROP TYPE "public"."enum__pages_v_blocks_audience_style_align";
  DROP TYPE "public"."enum__pages_v_blocks_audience_style_visibility";
  DROP TYPE "public"."enum__pages_v_blocks_process_style_width";
  DROP TYPE "public"."enum__pages_v_blocks_process_style_align";
  DROP TYPE "public"."enum__pages_v_blocks_process_style_visibility";
  DROP TYPE "public"."enum__pages_v_blocks_services_style_width";
  DROP TYPE "public"."enum__pages_v_blocks_services_style_align";
  DROP TYPE "public"."enum__pages_v_blocks_services_style_visibility";
  DROP TYPE "public"."enum__pages_v_blocks_testimonials_style_width";
  DROP TYPE "public"."enum__pages_v_blocks_testimonials_style_align";
  DROP TYPE "public"."enum__pages_v_blocks_testimonials_style_visibility";
  DROP TYPE "public"."enum__pages_v_blocks_contact_style_width";
  DROP TYPE "public"."enum__pages_v_blocks_contact_style_align";
  DROP TYPE "public"."enum__pages_v_blocks_contact_style_visibility";
  DROP TYPE "public"."enum__pages_v_blocks_project_grid_style_width";
  DROP TYPE "public"."enum__pages_v_blocks_project_grid_style_align";
  DROP TYPE "public"."enum__pages_v_blocks_project_grid_style_visibility";
  DROP TYPE "public"."enum__pages_v_blocks_profile_button_variant";
  DROP TYPE "public"."enum__pages_v_blocks_profile_style_width";
  DROP TYPE "public"."enum__pages_v_blocks_profile_style_align";
  DROP TYPE "public"."enum__pages_v_blocks_profile_style_visibility";
  DROP TYPE "public"."enum__pages_v_blocks_rich_text_style_width";
  DROP TYPE "public"."enum__pages_v_blocks_rich_text_style_align";
  DROP TYPE "public"."enum__pages_v_blocks_rich_text_style_visibility";
  DROP TYPE "public"."enum__pages_v_blocks_media_section_style_width";
  DROP TYPE "public"."enum__pages_v_blocks_media_section_style_align";
  DROP TYPE "public"."enum__pages_v_blocks_media_section_style_visibility";
  DROP TYPE "public"."enum__pages_v_blocks_cta_banner_button_variant";
  DROP TYPE "public"."enum__pages_v_blocks_cta_banner_style_width";
  DROP TYPE "public"."enum__pages_v_blocks_cta_banner_style_align";
  DROP TYPE "public"."enum__pages_v_blocks_cta_banner_style_visibility";
  DROP TYPE "public"."enum__pages_v_blocks_faq_style_width";
  DROP TYPE "public"."enum__pages_v_blocks_faq_style_align";
  DROP TYPE "public"."enum__pages_v_blocks_faq_style_visibility";
  DROP TYPE "public"."enum_theme_heading_font";
  DROP TYPE "public"."enum_theme_body_font";
  DROP TYPE "public"."enum_theme_heading_weight";
  DROP TYPE "public"."enum_theme_button_shape";
  DROP TYPE "public"."enum_theme_motion";
  DROP TYPE "public"."enum__theme_v_version_heading_font";
  DROP TYPE "public"."enum__theme_v_version_body_font";
  DROP TYPE "public"."enum__theme_v_version_heading_weight";
  DROP TYPE "public"."enum__theme_v_version_button_shape";
  DROP TYPE "public"."enum__theme_v_version_motion";`)
}
